### ISSUE TITLE
Getting the original array item from a v-repeated'd DOM element

### ISSUE THREAD

**Issue by TMiguelT** [vuejs/Discussion#112]
I've had this dilemma a few times with Vue. If I'm `v-repeat`ing over an array using Vue, and I have a reference to one of the HTML elements created by v-repeat, how do I then get the original object that was used to make it?

**Edit: this is a bad example of this problem because you can just pass in data to `v-on`. See below for a better example**

In this example I've got a reference to the HTML element through a `v-on` handler. How then do I get the `value` property of the DIV that was clicked?

```javascript
var vm = new Vue({
    el: "#parent",
    data: {
        ar: [{
            name: "a",
            value: 17
        }, {
            name: "b",
            value: 84
        }, {
            name: "c",
            value: 26
        }]
    },
    methods: {
        handler: function (a) {
            var element = a.target;
            //var value = ?? 
        }
    }
});
```

```html
<div id="parent">
    <div v-on="click: handler" v-repeat="ar">{{ name }}</div>
</div>
```

[Here's my attempt using a JSFiddle](http://jsfiddle.net/231d51ye/). I know that it works, but it's hacky and assumes the `name` property uniquely identifies the array element.

**Comment by bdaglish** [comment]
You can just pass value into the handler...

    <div v-on="click: handler(value)" v-repeat="ar">{{ name }}</div>

**Comment by TMiguelT** [comment]
Oh that was probably a bad example. In my case I have to use a jQuery event handler (because it's a jQuery event), so I can't pass in scope data. 

I suppose it's more like this: [Fiddle](http://jsfiddle.net/ws8w3mec/1/)
```javascript
var vm = new Vue({
    el: "#parent",
    data: {
        ar: [{
            name: "a",
            value: 17
        }, {
            name: "b",
            value: 84
        }, {
            name: "c",
            value: 26
        }]
    },
    ready: function(){
        $("#parent").on("click", "div", function(e){
			var el = e.target; 
			//el.innerHTML == "a"
			//How do I get the value 17?
		});
    }
});
```
```html
<div id="parent">
    <div v-on="click: handler" v-repeat="ar">{{ name }}</div>
</div>
```

**Comment by bdaglish** [comment]
There're a few ways of accessing the scope externally, but if you just want the single value, this little hack also works nicely...

    <div class="repeated" v-attr="title:value" v-repeat="ar">{{ name }}</div>
    ....
    alert("Clicked element with value \"" + el.title + "\"");

**Comment by TMiguelT** [comment]
Well if I'm doing that then I can just store the `$index` in an attribute, which will let me get any value I want. But the title attribute is displayed to the user if they hover over it, no? Is there another attribute I can use that won't mess things up?

**Comment by RangerMauve** [comment]
The recommended way to store data inattributes is to use a `data-*` attribute, which lets you access stuff via `element.data.set.*` as per the [dataset](https://developer.mozilla.org/en-US/docs/Web/API/HTMLElement.dataset) API.

**Comment by TMiguelT** [comment]
Oh wow. I didn't know that API existed. Although it looks like using `element.dataset` [won't work on](http://caniuse.com/#feat=dataset) IE (what did we expect), but it still looks like the best solution for the moment. 

Also @yyx990803 it looks like Angular has a method for this exact purpose [like this](http://stackoverflow.com/a/15756337/2148718). Would a similar API for Vue be a good idea? For example `Vue.element(el).scope()`

**Comment by yyx990803** [comment]
You can access the Vue instance bound to an element with `el.__vue__` (this is not a public API because it's not recommended).

**Comment by TMiguelT** [comment]
Okay thanks for the help. If `el.__vue__` isn't recommended, what is the best way to get the scope data in my second example (which is basically my use case).

**Comment by yyx990803** [comment]
It's more like trying to get scope data from the DOM node is not recommended, but if you need it you should use `el.__vue__`.

**Comment by TMiguelT** [comment]
Okay thanks for the help everyone!
