### ISSUE TITLE
Filter indexes

### ISSUE THREAD

**Issue by monolithed** [vuejs/Discussion#115]
##### What I have:

```html
<div class="foo  {{ index <= 3 ? 'bar' : '' }}" v-repeat="5" />
```

##### What I would like to get:
```html
<div class="foo bar" />
<div class="foo bar" />
<div class="foo bar" />
<div class="foo" />
<div class="foo" />
```

In other words I need to generate the five elements, but add an extra class only for the first three elements

And of course I can do something like:

```js
var demo = new Vue({
  el: '.foo',
  data: {
      values: [
                { index: 0 }
                { index: 1 }
                { index: 2 }
                { index: 3 }
                { index: 4 }
      ]
  }
});
```

Maybe there's a simpler solution?

**Comment by TMiguelT** [comment]
Your way will work, as in [this fiddle](http://jsfiddle.net/j0mw0aL7/1/). You just needed to use `$index` instead of `index`. However I think the better way of doing this is to use the `v-class` directive like this:
```html
<div class="foo" v-class="bar: $index < 3" v-repeat="5">SomeText</div>
```
[Here's a fiddle for v-class](http://jsfiddle.net/rgqnwr5y/)

**Comment by monolithed** [comment]
@TMiguelT, more thx!
