### ISSUE TITLE
How to build nested objects with or w/o v-repeat?

### ISSUE THREAD

**Issue by MadeMyDay** [vuejs/Discussion#119]
Hi,
I am new to vue.js but like what I see so far ;-) As also not very experienced in JS I hope you can forgive the perhaps stupid question(s).

What I want to build is a nested structure which consists of several components. While the tree example works well and can be easily adapted to use with dynamic components I struggle with the real data structure I will have in my app. It looks (simplified) like this:

```javascript
var items = [
    {
        title: "My Tree",
        id: 0,
        parentId: null,
    },
    {
        title: "child 1",
        id: 2,
        parentId: 0
    },
    {
        title: "child 2",
        id: 3,
        parentId: 0
    },
    {
        title: "child 1 of child 2",
        id: 4,
        parentId: 3
    }
]
```
Reason for that struture is to keep it flat and performant. This nested strutcture should easily hold a lot of items. What I tried was to use v-repeat. But then I get lost on the recursive child component.

So what I want to achieve:

1. List all items items with parentId null
2. List all child items of these root items (where parentId = id of the parent)
3. and so on

Displaying root level can be done with a custom filter (btw: filterBy only works as "contain", so not appliable here). But then I am lost. I am not able to pass some kind of childrens array as data source to the nested item. 

So my questions: Is this achievable with v-repeat at all? If not, how would you do that?
Related question: I also could build the markup "by hand" by iterating over the data json, but how I can I first generate dynamic markup and then apply Vue not until the markup is finished?

Thx for suggestions!

**Comment by TMiguelT** [comment]
Yes Vue and `v-repeat` absolutely support recursion. I'd never actually considered this problem but I had a lot of fun solving it! [Here's a JSFiddle](http://jsfiddle.net/18pdqg6r/4/) of a working solution. But I'll step you through it. 

The key thing to this is making a component that contains itself in the template. The way I did this is by creating a component called "tree-node", and setting its template to this:

```html
{{title}}
<ul>
	<li v-repeat="getChildren(id)">
		<tree-node></tree-node>
	</li>
</ul>
```

So each `<tree-node>` component contains its own title, and then starts a `<ul>` list which then contains an `<li>` for each child. I calculated the children by calling `getChildren()` with the tree-node's id, which runs over every element in the list (using ES5's [map](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Array/map)) and returns those whose parent is equal to the id we passed in. 

```javascript
getChildren: function (id) {
	return this.items.filter(function (el) {
		return el.parentId == id;
	})
}
```

But as I said, the key thing is that the `<li>` also has the `<tree-node>` component inside of it, which automatically has its `id` property set by v-repeat, so it will automatically populate its children.

**Comment by TMiguelT** [comment]
But having said all that, that data structure is fairly inefficient because for each element we have to look at each other element in the array, meaning `O(n^2)` comparisons, which isn't so bad for small lists, but if you had 1000 items you'd be doing a million comparisons (which I'm sure JavaScript can handle but it's not a *good* idea)

What would be better is to use the `id` field as the key in the parent data structure, and then storing an array of child IDs instead of a single parent id like this:

```javascript
var items = {
    "0": {
        title: "My Tree",
        children: [2, 3]
    },
    "2": {
        title: "child 1",
		children: []
    },
    "3": {
        title: "child 2",
        children: [4]
    },
    "4": {
        title: "child 1 of child 2",
        children: []
    }
}
```

[Here's a fiddle](http://jsfiddle.net/27b15xwk/) that demonstrates that your original data structures requires 20 comparisons for just those 4 items.
[Here's a fiddle](http://jsfiddle.net/ncn1opy3/1/) using the structure I've proposed. Note that it only does 4 lookups, meaning `O(n)` comparisons!

**Comment by MadeMyDay** [comment]
This was very helpful, thank you so much!

**Comment by kxxoling** [comment]
@TMiguelT This does not work on Vue 1.0, since `v-repeat` is replaced by `v-for`.
