### ISSUE TITLE
Can you explain the difference between v-if & v-show?

### ISSUE THREAD

**Issue by jcoffland** [vuejs/Discussion#122]
Also, I'm interested in knowing if either of these can be used to lazy load a group of child elements.  I.e. they are only compiled when the statement is true and are destroyed when it's false.

**Comment by RangerMauve** [comment]
What you're describing is how `v-if` works. It conditionally  renders that part of the tree. `v-show` just toggles `display:none`.

**Comment by jcoffland** [comment]
@RangerMauve, thanks!

As, a side note, ```v-if``` was not enough for my situation.  The problem I had was that the component ([CodeMirror](http://codemirror.net/), not a vue.js component in this case) being rendered was still being rendered while hidden causing the component to render incorrectly.  The solution was to use ```Vue.nextTick()``` in ```compiled()``` (or in ```bind()``` for a directive) to call ```CodeMirror.refresh()``` in addition to using ```v-if```.

**Comment by xgqfrms-GitHub** [comment]
https://vuejs.org/v2/guide/conditional.html
