### ISSUE TITLE
attached and ready not called when calling $appendTo detached DOM element

### ISSUE THREAD

**Issue by pkawiak** [vuejs/Discussion#125]
Hi,

Before I start I wanted to thank you for creating Vue. We're currently rewriting our app using your lib and so far it's awesome.

Please take a look at the following fiddle: http://jsfiddle.net/pkawiak/rbr8p3tf/

When I'm calling `$appendTo` on a Vue component instance with a reference to a DOM element which is attached to the document, `attached` and `ready` callbacks are executed.

Calling the same method with a reference to a detached DOM element prevents from executing those callbacks. That makes sense as it's not yet part of the document.

Now I'm appending that detached element to the document. I think that it would make sense to execute  `attached` and `ready` callbacks. Currently it's not the case. Is this a desired behavior?

**Comment by yyx990803** [comment]
This is a limitation of the current implementation - Vue currently cannot detect that the parent element was inserted. It is possible with MutationObserver, however it's really hard to provide consistent behavior in browsers that don't have it.

**Comment by pkawiak** [comment]
Hey, thanks for clarification. It's not a big issue. I've used `compiled` callback and it works fine.
