### ISSUE TITLE
how to set dynamic filter by vuejs

### ISSUE THREAD

**Issue by fqdeng** [vuejs/Discussion#1293]
so , I have a filter value like this 

data:{
age:  //it's a value bind by html input element 
person:[
{name:'dick',age:30},//and more
]
}

and I want to filer person age > age (value by user input) dynamic 
so , how to implament 

thanks

**Comment by fqdeng** [comment]
用中文再写一遍，英语太烂了

就是我想要一个动态过滤器，过滤的条件值是通过 控件input绑定的值，vuejs有没有简易的实现，

我之前用的是 clone两个数组，根据监控过滤值来决定是否显示值

**Comment by cmp-cc** [comment]
双向数据绑定，应当基于数据驱动开发。   示例:

https://jsfiddle.net/cmpcc/e8bjfuk0/

**Comment by fqdeng** [comment]
@cmp-cc
thanks 已经解决了这个问题，确实是要按照computed 来进行开发

**Comment by fqdeng** [comment]
@cmp-cc
thanks 已经解决了这个问题，确实是要按照computed 来进行开发
