### ISSUE TITLE
How to trigger a method at page load?

### ISSUE THREAD

**Issue by tiye** [vuejs/Discussion#13]
I create a navigation menu with vuejs for http://cirru.org/ and I got a problem.
I want it open a specified readme after page load.
The way it loads is a function I defined in `methods` property.
According to the docs, methods are not called from outside the scope.
How I am supposed to call the method with vuejs?

By the way, is that a good idea to create "vuejs" tag at StackOverflow and post questions there?

**Comment by janokary** [comment]
@ayamflow may I ask how to do the same if you are using broswerify? is it the same?

**Comment by niceperson** [comment]
pardon my noob question here.
so from my understanding using 
`var holder = new Vue({})`
is better then an anonymous
`new Vue({})`

thanks @ayamflow for indirectly enlighten me :)

**Comment by kaihendry** [comment]
In a .vue formatted component, how does one call a method on start? `this.test()` didn't work.

**Comment by kunKun-tx** [comment]
@kaihendry use ``mounted() {this.method}`` will call the method you want. It seems to get access to all page elements as well. just tested it with a div counter.

p.s. I found a little caveat using ``mounted`` alone. For reusable component with vue-router, make it be triggered by ``'$route' (to, from)`` via ``$watch`` to detect extra page(path) change. But

**Comment by aelkz** [comment]
`...
    methods: {
      login() {
        // do stuff here
      }
    },
    mounted() {
      this.login()
    }
...`

**Comment by sinanerdem** [comment]
When I try to use a method in my mounted, it gives an error like this:
"[Vue warn]: Error in mounted hook: "TypeError: vm is undefined""

My instance is like this:

```
var vm = new Vue({
	el: '#atcf',
	data: {
             // some data
  	},
  	methods:{
  		calculateAllowed() {
                   // some code
  	        }
  	},
  	created: function () {
  	},
  	mounted: function () {
  		this.calculateAllowed();
  	},
})
```
