### ISSUE TITLE
Improved dev tools

### ISSUE THREAD

**Issue by agonbina** [vuejs/Discussion#130]
I think we should have more advanced dev tooling for Vue.js. The [chrome extension](https://chrome.google.com/webstore/detail/vuejs-devtools/nhdogjmejiglipccpnnnanhbledajbpd?hl=en) is helpful, but something along the lines of the [MarionetteJS inspector](http://marionettejs.com/inspector/) would be awesome.

**Comment by yyx990803** [comment]
It'd be great if someone wants to work on a better version of it :)

**Comment by agonbina** [comment]
I might start working on it when I find some time. If I do I will post a link to the repo here as there might be others who have experience with building extensions and are willing to contribute. At the very least everyone can say what sort of information should we have on the extension. I'll put together a list of what I would find helpful when(and if :)) I start working on this.
