### ISSUE TITLE
Convert VueJS 1 to VueJS 2

### ISSUE THREAD

**Issue by nusendra** [vuejs/Discussion#1317]
i'm a vuejs beginner. i still dont know how to make this code work in vuejs2

https://codepen.io/jjelic/pen/yevNLZ?editors=1010

Please somebody help me to make that code work on vuejs 2.
Thank you very much.

**Comment by hamzaouiii** [comment]
Unfortunately, I am not available for personal support. This however is not an issue with Vue itself but rather a problem in your megration process. Please consider closing this issue and maybe post a question in stackoverflow. Even then I assume you might get any help as what you are asking for is a code writing service.

Take a look at the Vue 2 documentation and see what are the alternatives to your code and do it yourself. if you have a more specific problem, then maybe you can post a question on stackoverflow.

**Comment by nusendra** [comment]
yeah i know this is my personal problem. im a beginner in this js, so i  might have to learn more.

thanks anyway for your reply :)
