### ISSUE TITLE
Interpolation does not show anything for empty lists

### ISSUE THREAD

**Issue by wanderanimrod** [vuejs/Discussion#133]
Hi, 

Thank you for the good work you are doing on Vue.

I have spent a number of minutes banging my head against an apparent failure of vue to see the data I had put on my component.

__JS__
_________

var myComponent = Vue.extend({
...
data: function() {
        return {
            clients: []
        }
    }
...

__HTML__
__________
...
Clients = {{clients}}
...

__RESULTS__
______________
The resulting html was always "Clients = ".

I have just figured out that the html was 'empty' because my data was an empty list! 

1. Is this documented anywhere?
2. When clients = [{id: 1}], the resulting html is Clients = [object Object]
3. Is there a reason why doesn't it compile to the object literal, i.e in case 1, to "Clients = []" and in case 2 to "Clients = [{id: 1}]"?

Suggestion:
Having it compile to the literals helps a lot in debugging what is getting into the html.

Thanks.

**Comment by yyx990803** [comment]
You can pass it through the built-in `json` filter.

**Comment by wanderanimrod** [comment]
You are the best. Thanks
