### ISSUE TITLE
Sync data between a Parent VM and a component that uses the <content> tag

### ISSUE THREAD

**Issue by wanderanimrod** [vuejs/Discussion#135]
Hi good people, I have a form that I want to extract out into a component that will be consumed by about 4 other components, the only changes in the consumer components being the actions one can take on the form. So, I was thinking about making the form component have a ```<content>``` insertion tag where consumer components would insert their form action buttons.

The problem is that the methods that the specialised buttons will execute will be on the parent-vms yet the form data that the custom actions process is on the base-form component. Is there a way to pass data down to a component's inserted ```<content>``` so that that data will be available on the consumer VM, referred to as 'the Parent VM' in [Vue docs](http://vuejs.org/guide/components.html#Content_Insertion) ?

Here is some pseudo code describing the problem

```
//base-form-component.js
baseForm = {
    template: require('./base-form-template.html'),
    data: function() {
        return {
            client: {
                name: 'Jon Doe',
                age: 34
            }
        }
    }
}

________________________________________________________

<!-- base-form-template.html --> 
<form>
    <input id=name value="{{ name }}">
    <input id=age value="{{ age }}">
    <content>Here is where the custom submit buttons of consumers will be inserted. Those buttons' will perform actions that need to know what data is in the client object.</content>
</form>

_________________________________________________________________

parentVM = {
    template: require('./parent-template.html'),
    components: {
        'base-form-component': require('./base-form-component.js')
    },
    methods: {
        createNewClient: function() {
            //pick client from base-component vm and submit via http call.
            //QUESTION: How do you pick the most recent data from the base               component vm?
        }
    }
}

_______________________________________________________________

<!-- parent-template.html -->
<base-form-component>
    <button class="submit" v-on="click: createNewClient()"></button>
</base-form-component>
```

How do I make sure the parent vm's createNewClient method knows about the base-form-component's client data object when the submit button in the parent-vm-template is clicked?

**Comment by dgerber** [comment]
Hi,
`<base-form-component v-ref="form">`, then in createNewClient you can access data on the child vm as `this.$.form.client`.

**Comment by wanderanimrod** [comment]
Thanks a lot!
