### ISSUE TITLE
How can i use moustache binding in v-if of Vuejs

### ISSUE THREAD

**Issue by eranshul26** [vuejs/Discussion#136]
i have the following code

< div v-repeat="obj1 : MainObject" >
< div v-repeat="obj2 : InnerObject" >
< div v-if="{{$key}}=={{$parent.$key}}" >
print something
< /div >
< /div >
< /div >

I want to use the dynamic values in v-if based on iteration object key... How can i use the moustache binding in v-if. It is not allowing me to do like this.. Is there any other way?

**Comment by RangerMauve** [comment]
You should be able to just do
``` html
<div v-if="$key == $parent.$key"></div>
```

**Comment by eranshul26** [comment]
Thanks  :) It worked
