### ISSUE TITLE
#Vuejs: How to check if a vue component witha particular name already created

### ISSUE THREAD

**Issue by eranshul26** [vuejs/Discussion#140]
Hi,

My code is creating the vue component dynamically like below:

```javascript
Vue.component('CompOne', {
    		'template':"<div>test</div>"
    	});
```

I want to check if a component with name 'CompOne' already exist then it should not create another component with same name.

please suggest me the way how to check if a vue component with some name is already created.

Thanks

**Comment by eranshul26** [comment]
@yyx990803 

Could please let me know the way out...

**Comment by yyx990803** [comment]
You can check if `Vue.options.components['CompOne']` exists.

**Comment by eranshul26** [comment]
Hey Thanks...
