### ISSUE TITLE
the nodes destroy issues

### ISSUE THREAD

**Issue by lbs007ty** [vuejs/Discussion#145]
use the chrome dev tools watch the timeline when you switch the component, then you will see that the nodes number is continue to increase, even you are switch the same two component.

**Comment by yyx990803** [comment]
Even if you just repeatedly set the `innerHTML` of a node, you will see the number of Nodes increase over time because there has been no GC event yet.

The proper way to profile this is take multiple memory heap snapshots (which forces GC) and compare them.

**Comment by lbs007ty** [comment]
i know that.  but the GC will be trigger when stop the dev record.  just compare with the number of restart record then will know.

**Comment by yyx990803** [comment]
Just stopping recording doesn't force GC... you need to click the GC button (the trash can) before stopping recording....
