### ISSUE TITLE
Simple Example: Wut am i doing wrong...

### ISSUE THREAD

**Issue by simondavies** [vuejs/Discussion#146]
I have the following code and am seeing nothing: What am i doing wrong or missing.
```
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <title>VUE JS</title>
</head>
<body>
   <div id="demo">
      {{message}}
      <input v-model="message">
    </div>

    <script type="text/javascript" src="js/vue.min.js" />
    <script>
        (function() {
                var vm = new Vue({
                      el: '#demo',
                      data: {
                        message: 'Hello Vue.js!'
                      }
                    });
        })();
    </script>
</body>
</html>
```
mac using chrome

**Comment by yyx990803** [comment]
Can't see anything wrong with the code, is there any error message in the console?

**Comment by simondavies** [comment]
thanks for getting back to me.  I don't see anything in the console, if i console.log(vm), or any console.log('text') still nothing, so its not getting to the second scrtip tag by the looks of it. I get the {{message}} (input field ) on the browser and thats it.

**Comment by azamat-sharapov** [comment]
I think this issue has nothing to do with Vue.js. File `js/vue.min.js` is not accessible maybe. [Here is fiddle using your code](http://jsfiddle.net/azamatsharapov/dr4gnjp8/).

**Comment by simondavies** [comment]
thats what i thought but strange i even place the <script src="js/vue.min.js" /> at the top of the file and it does not display anything, its as if its blocking it but not returning any type of error. Copied the raw vue.min.js raw form git and tried this but nothing.

Do i need to use other ways to create and cal in, like require etc? With that fiddle you attached, how come it does not show a framework on the side list?

**Comment by yyx990803** [comment]
Oh, your first script tag needs to be closed:

``` html
<script type="text/javascript" src="js/vue.min.js"></script>
```

You can't close a script like this `<script ... />`, it will not parse correctly.

**Comment by azamat-sharapov** [comment]
wow, you have super glasses Evan :D

**Comment by simondavies** [comment]
doh! that'll teach me to except sublime text auto fill sometimes :-) for the life of me you stare and stare and doh!  thanks @yyx990803

**Comment by soulmachine** [comment]
Here is a minimal example:

``` html
<!DOCTYPE html>
<html>
  <head>
    <script src="http://cdn.jsdelivr.net/vue/2.0.3/vue.js"></script>
  </head>
  <body>
    <div id="app">
      <p>{{ message }}</p>
    </div>
    <!-- Must put the script after the app div -->
    <script type="text/javascript">
      new Vue({
        el: '#app',
        data: {
          message: 'Hello Vue.js!'
        }
      })
    </script>
  </body>
</html>
```
