### ISSUE TITLE
How VueJS combine with jQueryUI perfectly?

### ISSUE THREAD

**Issue by danielchou** [vuejs/Discussion#147]
Hi,
I have a form with date input bind with v-model and build with jQuery UI datepicker. So far I can get this value and pass through the model, please see [example](http://jsbin.com/xuyiva/2/edit?html,js,console,output), however, I do not prefer the way directly pass value. I see Vue 0.11.6 now supporting the jQuery event, could someone have a better way to handle this?

**Comment by opheliadesign** [comment]
Having the some problem, was this ever solved completely? I'm using Bootstrap DateTimePicker

**Comment by yyx990803** [comment]
See this thread: https://github.com/yyx990803/vue/issues/812#issuecomment-97852184

**Comment by opheliadesign** [comment]
Thanks, this works great for setting but how about resetting? For example, I’m adding a new object to an array. I can now get the dob field but when I clear it in the newCamper object (model bound to the dob input), the date that was set with date picker remains.

**Comment by jenswaern** [comment]
@opheliadesign did you ever get this figured out? I'm having a similar problem with an array of objects and jQuery UI datepicker.

**Comment by happilymarrieddad** [comment]
@opheliadesign be careful with bootstrap datetimepicker.. it has a memory leak. We were having issues with it for a while on our production server and after I removed it the problems went away.
