### ISSUE TITLE
v-repeat branching on data type

### ISSUE THREAD

**Issue by natishere** [vuejs/Discussion#148]
if i v-repeat on an object i get $index $key and $value
if I v-repeat on an array i get $value

I would like to v-repeat on an unknown value (of an object key) and branch on the type (object key-vals  or array values)

I can't seem to be able to test on the type.

**Comment by yyx990803** [comment]
You can basically branch based on the presence of `$key`, since array repeats won't have that property.

**Comment by natishere** [comment]
I tried that but couldn't quite get it. here's the gist of what I'm trying to do:

<div v-repeat="$data">     
         <template v-if="$key" >
         <ul>
         <li>{{$key}}: {{$value}}</li>
         </ul>
         </template>
         <template v-if="! $key" >
         <ol>
         <li>{{$value}}</li>
         </ol>
         </template>
      </div> 

Thanks so much for your help and for a product I very much like!

**Comment by azamat-sharapov** [comment]
@natishere could you make jsfiddle if possible? i'm also interested :)

**Comment by natishere** [comment]
jsfiddle (needs fixing): https://jsfiddle.net/20hjcL7w/

**Comment by azamat-sharapov** [comment]
Your data structure seemed confusing to me, but have a look: https://jsfiddle.net/azamatsharapov/vhz1a5p2/1/ - is that something you are trying to get?

**Comment by natishere** [comment]
Thanks azamat-sharapov - better - but what if I didn't know in advance that one of the keys was 'name'?

**Comment by azamat-sharapov** [comment]
Well, you could pass method to `v-if`, like so: https://jsfiddle.net/azamatsharapov/vhz1a5p2/2/
But maybe @yyx990803 will come up with better idea.

**Comment by yyx990803** [comment]
@azamat-sharapov 's solution looks pretty clean to me.

Note in your original fiddle that `$value` is only available if the current data being repeated on is a primitive value. In your case, it's an object, so that object is used as the `$data` inside that repeat block.

Directly referring to `$data` and `$value` can be confusing with nested repeats, so it's recommended to use identifiers.

**Comment by natishere** [comment]
Certainly something I can work with @azamat-sharapov ! Thanks much!
I had tried identifiers and trying to ascertain their type to no avail. That's why I went back to the $data that was sure to exist. Thanks both.
