### ISSUE TITLE
How to make element repeat N times?

### ISSUE THREAD

**Issue by germansokolov13** [vuejs/Discussion#150]
I need an element be repeated as with `v-repeat` but not for each array element but rather N times where N is some Vue's property of type number. I don't know how to do it with custom directives or components. Maybe it would be useful to create some sort of a `v-times` predefined directive? Or maybe I am missing something?

**Comment by yyx990803** [comment]
You can just do `v-repeat="10"`, or it can also be bound to a numeric value: http://vuejs.org/guide/list.html#Iterating_Over_a_Range

**Comment by germansokolov13** [comment]
Oh, woops, I didn't nitice it.

**Comment by thehowl** [comment]
For those who stumble on this issue while looking for a solution: in vue 2 it is actually [`v-for="n in 10"`](https://vuejs.org/v2/guide/list.html#Range-v-for)

**Comment by dractw** [comment]
I found this a few days ago, looking for a solution on how to v-for a large array not entirely, but for N-elements for the first pass:

`<p v-for="(item, index) in array, N"> N times v-for</p>`

Actually, didn't found this in documentations, or didnt seek so good

**Comment by LinusBorg** [comment]
This repository is deprecated, please use forum.vuejs.org
