### ISSUE TITLE
Reason for $add returning when key exists

### ISSUE THREAD

**Issue by holic** [vuejs/Discussion#153]
I'm using `$add` in place of setting a property on an observed object and found that any new values weren't being set after the first call. Digging into the code, I found that `$add` returns when the key already exists. Why is that?

https://github.com/yyx990803/vue/blob/51cfffbdba03b937f0ef8efe40a87521852d601e/src/observer/object.js#L17

**Comment by azamat-sharapov** [comment]
To change value of existing property, you have `$set`.
`$add` speaks for itself - it **adds** property, not update like. `$set` though, will **add** too, if property doesn't exist.

**Comment by yyx990803** [comment]
The purpose of `$add` is to explicitly add an observed property. If that property already exists and is observed, it will have no effect.

@azamat-sharapov `$set` is actually only available on the vm instance, not on nested observed objects. Maybe I should add that to normal objects too...

**Comment by azamat-sharapov** [comment]
oh I see, haven't used it for observed object yet

**Comment by holic** [comment]
That's where I was getting caught up - on observed objects, not VM instances. It would be great if I could use `$set` on observed objects instead of explicitly checking for key existence, then setting or `$add`ing.

**Comment by yyx990803** [comment]
$set is now implemented in dev branch: 00d423d

**Comment by holic** [comment]
Thanks @yyx990803!

**Comment by holic** [comment]
@yyx990803 Would it also make sense to implement `$get` for consistency with VM data?

**Comment by yyx990803** [comment]
vm's `$get` and `$set` serve slightly different purposes: they also accept key paths, and can be useful in other situations. Object `$set` is only to make sure the set triggers an update.

**Comment by holic** [comment]
:+1:
