### ISSUE TITLE
0.12 Upgrade - removing v-wtih

### ISSUE THREAD

**Issue by cretueusebiu** [vuejs/Discussion#159]
Until  now I've been passing data using `v-with` and  I want to move away from it.

I had an alert component: 

     Vue.component('alert', {
	     template: '#alert-template'
     });

and I used it like this, passing the `errors` using `v-with`:

    <div v-component="alert" v-with="errors: errors"></div>

Now I moved to tags only:

   <alert-component errors="{{errors}}"></alert-component>

But the `errors` are not passed into the alert component.

I've solved it with: 

    components: {
        'alert-component': {
            paramAttributes: ['errors'],
            template: '#alert-template',
        }
    },

but I have to write that each time I want to use the alert component.

Is there any way I can still have my alert component defined like before and pass the errors without having to add each time the component in the `components`  ?

**Comment by yyx990803** [comment]
I'm not quite understanding the issue. Why can't you still make it global?

``` js
Vue.component('alert-component', {
  paramAttributes: ['errors'],
  template: '#alert-template'
});
```
