### ISSUE TITLE
Methods vs. 1-way Filters

### ISSUE THREAD

**Issue by aristidesfl** [vuejs/Discussion#168]
At first glance Methods and 1-way Filters seem to offer the same functionality, differing only in style:
`v-text="method(property, arg2, arg3)"` vs `v-text="property | filter arg2 arg3"`

The only difference seems to be that, when used with `v-model`, methods don't update the model automatically.

Are there any other practical differences between the two?

**Comment by yyx990803** [comment]
Semantically, this differentiates `methods` vs. `filters`: the former indicates possible side effects or state mutations; the latter by definition should be idempotent functions with no side effects.

**Comment by aristidesfl** [comment]
Sounds like a good rule of thumb to follow. Thank you for the help.
