### ISSUE TITLE
"Chunking" view data

### ISSUE THREAD

**Issue by mattkoch614** [vuejs/Discussion#177]
Is there a "best practice" for "chunking" Vue data into pieces when the plan is to segment the view into specific rows and columns (for example, with Bootstrap's grid system? http://getbootstrap.com/css/#grid)

The only method I've been able to come up with is to define a secondary array in my Vue instance to hold the chunks, and re-calculate them after each addition to the "main" data array.

Here is a JSBin of what I'm looking to achieve, which is working pretty much as intended:
http://output.jsbin.com/yuruqugela

**Example:**

```
methods: {
...
 reChunk: function(options) {
     var self = this;
     self.chunks = [];
     var i, j, temparray, chunk = 4;

     for (i = 0, j = self.items.length; i < j; i += chunk) {
         //here is where we slice up the acual data items into chunks
         temparray = self.items.slice(i, i + chunk);
         self.chunks.push(temparray);
     }
 },
...
```

**Comment by visualcom** [comment]
Maybe:

```
computed: {
   chunkedItems () {
     return _.chunk(this.items,4)
   }
}
```

**Comment by usamamashkoor** [comment]
@visualcom can you please explain your answer please..?

**Comment by visualcom** [comment]
Hi @usamamashkoor , In the example above I'm using [Lodash chunk method](https://lodash.com/docs/4.17.4#chunk).

_.chunk(array, [size=1]);

Example:
_.chunk(['a', 'b', 'c', 'd'], 2);
// => [['a', 'b'], ['c', 'd']]

From Lodash documentation:
"Creates an array of elements split into groups the length of size. If array can't be split evenly, the final chunk will be the remaining elements."

Hope this helps!

**Comment by usamamashkoor** [comment]
Thanks man..

**Comment by mattkoch614** [comment]
I've since transitioned to using a computed property for this type of thing as well. It sounds like this is the appropriate way to go, so I'll close this thread.
