### ISSUE TITLE
Pagination and filters

### ISSUE THREAD

**Issue by mantasmo** [vuejs/Discussion#181]
I guess this is somewhat related to https://github.com/yyx990803/vue/issues/872 though I'm not 100% sure what the other author meant.

I'm trying to figure out a clean way to get the length (total pages for pagination) of a list after filtering. As it stands now everything works fine except when I filter the list of users down to say one name there are still four pages shown in pagination (obviously). What would be the nicest way to update the number of pages dynamically as well?

A - very simplified - fiddle: https://jsfiddle.net/mantasmo/os7hp1cy/10/

Thanks!

**Comment by yyx990803** [comment]
Although in theory filters should not produce side effects, in this case it is probably necessary. You can modify the vm state in your `paginate` filter: https://jsfiddle.net/os7hp1cy/11/

**Comment by young-steveo** [comment]
It would be cool if filters could be injected into computed property functions of the VM:

```js
new Vue({
    /* ... */
    computed: {
        totalPages: function(filterBy, paginate) {
          var filtered = filterBy(this.users, this.searchKey);
          return Math.ceil(paginate(filtered).length / this.itemsPerPage)
        }
    },
    /* ... */
    filters: {
        paginate: function(list) {
            var index = this.currentPage * this.itemsPerPage
            return list.slice(index, index + this.itemsPerPage)
        }
    }
})
```

**Comment by yyx990803** [comment]
@young-steveo you can do that by calling

``` js
var filterBy = this.$options.filters.filterBy
var filtered = filterBy.call(this, this.users, this.searchKey) // make sure to call the filter with proper context
```

**Comment by young-steveo** [comment]
@yyx990803 :+1:

**Comment by mantasmo** [comment]
Yea I was trying to avoid having to modify state inside a filter. Looks like using a computed property is the way to go. Thanks both of you!

Also: @yyx990803 thank you for vuejs!

**Comment by mantasmo** [comment]
@yyx990803 just a heads up - your example fiddle works fine using vue 0.11 but doesn't behave properly using 0.12-rc2 - after filtering through the list pagination stops responding.

**Comment by yyx990803** [comment]
Yes, I've noticed that, and it's been fixed in latest `dev`. (Note the fiddle itself also had a logic bug at the line `this.currentPage = this.totalPages - 1`, it should be `this.currentPage = Math.max(0, this.totalPages - 1)`)

**Comment by Jazzis18** [comment]
@yyx990803 i'm using 1.0.21 production version and a bug that described @mantasmo above, there is in it, but in a development version the filtering works fine.
