### ISSUE TITLE
binding to html strings

### ISSUE THREAD

**Issue by natishere** [vuejs/Discussion#182]
viewModel has:
      HTMLstring:  "this is a \<b>bold\</b> statement"

but when I use it in span:
     \<span>{{HTMLstring}}\</span>

I don't get the expected result.

any advice?

**Comment by yyx990803** [comment]
Use triple for unescaped HTML: `{{{ html }}}`. But make sure you understand the security implications of doing so.

**Comment by natishere** [comment]
PERFECT!  I did read this in docs a while back but hadn't used it.
Thanks!
