### ISSUE TITLE
Delaying performance-heavy computed attributes.

### ISSUE THREAD

**Issue by Nirazul** [vuejs/Discussion#184]
Hey there!

I'm in the final stages of completing a Vue.js app and running into some performance problems on weaker devices like an iPad.
The starting page contains a button panel by which you get to the second page. 
When selecting one of the options, a rather performance hungry computed attribute eats away around 300ms (on iOS Safari, which has a rather slow js engine) until the second screen (changing a dynamic component) shows up.

What is the best way to decouple a computed attribute from rendering the new state? Is there a better pattern to implement tasks that would block the UI for so long?

**Comment by yyx990803** [comment]
One possible solution is to implement some sort of short-circuit in your computed property:

1. add a `loading` state to your component
2. in the computed property, if `this.loading`, just return `null` or some mock data immediately
3. since the computed property depends on `loading`, when you set `loading` to true later, the computed property will run again.

This is sort of a last-straw approach though, I think it's probably a good idea to avoid any heavy computation in computed properties as they are evaluated every time they are accessed.

**Comment by yyx990803** [comment]
I'm also curious why this computed property takes up so many times - are you accessing it elsewhere multiple times? Can you check how many times it's been called during the render of the component?

**Comment by Nirazul** [comment]
Thanks for the suggestion, I'll give it a try!

These were the first things I've optimized. I made sure that the computed property now gets called only once per data alteration.

The component is a Filterpanel that loads around 8-9 selectors with selectable options. There's a list of recipes that define the options that are present in every filter. When I select one option in a filter, the recipes are being filtered and every other filter must be updated in order to remove the options no longer present.

```
FilterPanel:
    Filter > [filterOption, filterOption, ...]
    Filter > [filterOption, filterOption, ...]
    Filter > [filterOption, filterOption, ...]
    Filter > [filterOption, filterOption, ...]
    Filter > [filterOption, filterOption, ...]

Recipes:
Recipe > [filterOption, filterOption, filterOption, filterOption, filterOption]
Recipe > [filterOption, filterOption, filterOption, filterOption, filterOption]
Recipe > [filterOption, filterOption, filterOption, filterOption, filterOption]
Recipe > [filterOption, filterOption, filterOption, filterOption, filterOption]
```

The app should work without a server, so I need to filter everything dynamically on the client.
