### ISSUE TITLE
Track original $index with v-repeat after filter

### ISSUE THREAD

**Issue by butsalt** [vuejs/Discussion#187]
Hi, I'm using vue to build a bar chart. Each bar group is a component.
## What I try to implement is:
Through click checkbox , hide/show target bargroup .
## My data like this:
```javascript
var barGroups = [{
	id: "first",
	isShowing: true,
	items: [{
		x: "2012-12-24",
		y: 30
	},{
		x: "2012-12-25",
		y: 50
	},{
		x: "2012-12-26",
		y: 60
	}]
},{
	id: "second",
	isShowing: true,
	items: [{
		x: "2012-12-24",
		y: 50
	},{
		x: "2012-12-25",
		y: 70
	},{
		x: "2012-12-26",
		y: 10
	}]
},{
	id: "third",
	isShowing: true,
	items: [{
		x: "2012-12-24",
		y: 30
	},{
		x: "2012-12-25",
		y: 30
	},{
		x: "2012-12-26",
		y: 80
	}]
}]
```
## So I implement in this way:
Through click checkbox, target bargroup's isShowing(property) will be set to true/false
I use v-repeat with filterBy to decide which bargroup to show.
I need $index(after filter) to calculate the position of each bar in each barGroup. Every bar I Use property x to calculate position in timeline, then use $index to make translate in time group.
But I also need $index(before filter) to decide bargroup's color.
## There is my example:
Before click:
![image](https://cloud.githubusercontent.com/assets/8847427/8128454/ae1da344-1131-11e5-89b2-98cb331ffce9.png)
After click( middle bar group is beiing hiddened, but color is wrong ):
![image](https://cloud.githubusercontent.com/assets/8847427/8128445/967bdf94-1131-11e5-8a78-e24fd72c23cb.png)

**Comment by yyx990803** [comment]
I don't think you should rely on the original $index - IMO the bars should be colored based on what type they represent, and that type information should be part of the data.

**Comment by butsalt** [comment]
That's a good idea, thanks
