### ISSUE TITLE
Change component $data via prop

### ISSUE THREAD

**Issue by OEvgeny** [vuejs/Discussion#189]
I need to change whole ``$data`` of component via props.
```
 <component is="{{comp.name}}" $data="{{com.data}}"></component>
```
It works well, but I get ``$data:null`` in component ``$data``
See fiddle: http://jsfiddle.net/nofv7zpo/1/

**Comment by yyx990803** [comment]
This is no longer the case in latest `dev` :)

**Comment by OEvgeny** [comment]
Oh, yes works perfect. Thanks!
