### ISSUE TITLE
How can I add component(or directive) in directive

### ISSUE THREAD

**Issue by akifo** [vuejs/Discussion#192]
I think this question is easy javascript subject.
but, there aren't a lot of example for Vue.js.

[sample code( it doesn't work ) in jsfiddle](https://jsfiddle.net/akiho/L83h0fvv/)

This is working,
when the code change following

add the tag
```html
<div v-design="design1">
  <hover count="{{design1.count}}"></hover>
</div>
```
remove the line
```javascript
$(this.el).append('<hover count="{{'+this.expression+'.count}}"></hover>');
```

How can I add dynamically component(or directive) in directive ?
Thanks.

**Comment by yyx990803** [comment]
It is not recommended to dynamically inject HTML content when using Vue - instead, try to think top-down about your application structure, and clearly divide your view into components. If something needs to be displayed conditionally, use `v-if`.

It is of course possible to dynamically compile a piece of HTML at run time, but it's considered advanced usage: http://vuejs.org/api/instance-methods.html#vm-\$compile\(_element_\)

**Comment by akifo** [comment]
> clearly divide your view into components.

This is absolutely true.

I found what I wanted.
The key is  ``content``!
> the entire original content will be inserted at its position in the DOM and replaces it.

I just wanted to do like following:
- Custom component has different element.
- and of course, has same element and same directive.

[sample code in jsfiddle](https://jsfiddle.net/akiho/L83h0fvv/3/)


thanks for comment.
