### ISSUE TITLE
attached method in a plugin?

### ISSUE THREAD

**Issue by mark-hahn** [vuejs/Discussion#195]
I am writing a plugin to keep the scroll position of elements when they are detached and reattached.  My non-working code is ...

```
vueKeepScroll = 
  install: (Vue) ->
    Vue.directive 'keep-scroll',
      bind: ->
        @el.addEventListener 'scroll', (e) ->
          ele = e.target
          ele.setAttribute 'data-vuescrlpos', "#{ele.scrollLeft}-#{ele.scrollTop}"
        oldAttached = @vm.attached
        @vm.attached = (args...) ->
          for ele in @$el.querySelectorAll '[data-vuescrlpos]'
            [ele.scrollLeft, ele.scrollTop] = ele.getAttribute('data-vuescrlpos').split '-'
          oldAttached?.call @, args...
```
Note that I need to be notified after an attachment.  I am adding the function `this.vm.attached` but it is never called.  I have determined that it is being added properly at plugin directive bind time.

Why isn't it called?  Is there a better way be notified of an attachment in a plugin?

**Comment by yyx990803** [comment]
The lifecycle hooks fire as events. You need to do `@vm.$on 'hook:attached', (args...) -> ...`

**Comment by mark-hahn** [comment]
thanks
