### ISSUE TITLE
在微信里打开web使用显示空白

### ISSUE THREAD

**Issue by zb188** [vuejs/Discussion#196]
微信里打开网页 空白的 
浏览器地址
http://4.hotel.hqkeji.cn/page/venue/index
扫码看下
![微信扫一扫](http://i4.tietuku.com/c1b2e62ca71b4248.png)

**Comment by yyx990803** [comment]
码的图片加载不出来。你用的手机什么操作系统？

**Comment by zb188** [comment]
安卓

**Comment by yyx990803** [comment]
我要的是版本啊大哥... 光告诉我安卓有毛用？

**Comment by zb188** [comment]
问题已经找到了，是后端配置问题，造成微信获取openid请求报错，后面js无法执行
