### ISSUE TITLE
sortBy doesn't allow case insensitive sorting

### ISSUE THREAD

**Issue by ColBatGuano** [vuejs/Discussion#197]
I currently have a v-repeat for a table...
```
<tr v-repeat="items | orderBy sortKey reverse">
```
but I can't see how to sort this in a case insensitive manner. 
Perhaps this could be done via a case insensitive variant of orderBy, or perhaps by allowing a comparison function to be supplied.

**Comment by yyx990803** [comment]
If you need custom sorting logic you can always just write your own custom
filter. Just remember to sort on a copy of the original array.

**Comment by ColBatGuano** [comment]
Interestingly the filterBy does case insensitive filtering.

Thank you for that, i'll go and write one.
