### ISSUE TITLE
Are computed values propagated?

### ISSUE THREAD

**Issue by mark-hahn** [vuejs/Discussion#198]
*I'm sorry to ask so many newbie questions.  When I'm an expert I will help answer questions.*

I have the value `curEpisodeIdx` computed and I want the value passed to component `curPage` automatically.  This doesn't seem to work.  Are computed values automatically computed when dependent values are changed?

```
   { 
      template: {
        '<component is="{{curPage}}"  cur-episode-idx="{{curEpisodeIdx}}" >
          ...
      },
      data:  {
        curShow: 0 
      },
      computed: {
        curEpisode: function() {
          return this.curShow.episodes[this.curEpisodeIdx]
        },
        curEpisodeIdx: {
          get: function() {
              return Math.min(this.curShow.episodes.length-1, this.curShow.episodeIdx)
          },
          set: function(val) {
             this.curShow.episodeIdx = Math.min(this.curShow.episodes.length, val)
          }
        }
      }
    }
```

Should I use a `$watch` instead?

**Comment by yyx990803** [comment]
This should work, can you reproduce it?

**Comment by mark-hahn** [comment]
I rewrote it and it works now.  I didn't keep the older version so I don't know what I did wrong.  I'm happy to find out this works.

Sorry for your trouble.
