### ISSUE TITLE
v0.12.2 proposed changes

### ISSUE THREAD

**Issue by yyx990803** [vuejs/Discussion#201]
- Default `replace` option to true.
  - < 0.12.1 apps can easily preserve original behavior by setting `Vue.options.replace = false`.

- [x] Bring back partials, but with a different syntax that is more consistent with the `<component>` and `<content>` syntax:

  ``` html
  <!-- static partial -->
  <partial name="my-partial"></partial>
  <!-- dynamic partial -->
  <partial name="{{partialName}}"></partial>
  ```

- [x] Adjust the compilation order so that props are available in `data` hooks.

---

#### To be considered for later releases

- Remove `delimiters` from the global `Vue.config` and make it a component-level option. Its default can still be modified globally by setting `Vue.options.delimiters = ...` but it is recommended to use it on a per-component level. The reason for this change: changing global delimiters breaks interop with 3rd party components.
- Probably need to do the same for `Vue.config.prefix`

**Comment by danmindru** [comment]
Setting `replace` to true by default is a great idea.
Other changes make sense too.

Sort of related: I find it annoying to use curlies to pass variables to components. 90% of the cases we want to pass a variable or method, but string is default.
I think it would be reasonable to use quotes for strings & default vars/methods.

```
Variable ->
<comp name="myName"></comp> 

String ->
<comp name="'myName'"></comp>
```

**Comment by OEvgeny** [comment]
New partials syntax looks good.

**Comment by yyx990803** [comment]
@danmindru the reason for required curlies in props is so that we can easily differentiate dynamic props  from normal attributes.

**Comment by Nirazul** [comment]
Great changes, gonna love the partial syntax :+1:

**Comment by zhongqf** [comment]
+1 for removing double curlies when pass variables to components. It is more clear.

**Comment by azamat-sharapov** [comment]
In terms of readability, I think with curlies it's easier, so we know it's dynamic variable there. Also, [when it comes to passing boolean](http://jsfiddle.net/azamatsharapov/z5ptdmdn/), current implementation makes much more sense that another proposal.

I would like to propose `$context` feature for easier parent -> sub-children communication (or something similar to that). We already discussed with Evan. But I totally understand if it comes later, as this probably requires much coding.

**Comment by kazupon** [comment]
:+1:

**Comment by young-steveo** [comment]
Default replace `true` and the new partial syntax are awesome! :+1: :+1:
