### ISSUE TITLE
How to pass  " data-parsley-range='[6,10]' " to an element through a component (props).

### ISSUE THREAD

**Issue by zezont4** [vuejs/Discussion#211]
I really like Component system, but so far , there one problem that is stopping me from using it, and I didn't figure out how to solve it.

How can I pass something like this : ( `data-parsley-range="[6,10]"` ) to an element through a component (props).

Example:
### JS Code:
```javascript
Vue.component('my-component', {
    template: '<input type="text" {{{ this.customAttribute }}} >',
    props: ['custom-attribute']
});

new Vue({el: '#demo'});
```

### HTML Code:
```html
<div id="demo">
<my-component custom-attribute='data-parsley-range="[6,10]"'></my-component>
</div>
```
I tried Custom Directives but I failed !

Is there a way to do it?

It's very important to me .

Thank you.

**Comment by azamat-sharapov** [comment]
you don't have to use `this` in templates, just property name: `customAttribute`

**Comment by azamat-sharapov** [comment]
also, I think it would be cleaner to pass array of attributes:

```
Vue.component('my-component', {
	template: '<input type="text" v-el="elem" >',
	props: ['custom-attributes'],
	ready: function() {
		// loop through customAttributes
		// and set attrs for elements like so:
		// this.$$.elem.setAttribute(key, val)
	}
});

new Vue({
	el: '#demo',
	data: {
		attrs: [
			{'data-parsley-range': '[6,10]'}
		]
	}
})

<div id="demo">
	<my-component custom-attributes="{{attrs}}"></my-component>
</div>
```

**Comment by zezont4** [comment]
Brilliant idea .
Thank you.

It works
