### ISSUE TITLE
initialize v-repeat vm on existing data

### ISSUE THREAD

**Issue by johannes-z** [vuejs/Discussion#217]
Is there an easy way to register a set of elements on a viewmodel, if the data already exists? I didn't find anything for this in the docs. 
What I basically want is to improve the responsiveness...
Use case:
* Server side rendering for the initial set of data (f.e. 5 messages).
* Register the data in the viewmodel (f.e. to add delete/update functionality).
  * Register events: remove the oldest message, if the hard limit of 5 messages has been reached, and a new message has been added.

I created a very basic jsfiddle, giving you an idea on the layout I've got. 
https://jsfiddle.net/4smfrjrr/3/

**Comment by azamat-sharapov** [comment]
AFAIK, vue doesn't provide such functionality. If you have control over server side app, you should return JSON object and render it on server.
Another way would be extra javascript to parse you HTML and make JSON out of it, but you probably don't what that..

**Comment by johannes-z** [comment]
Actually, I think it's kinda impracticable. You would have to do the same thing once for the server side rendering, and once for the client side rendering.
