### ISSUE TITLE
关于 component 的困惑

### ISSUE THREAD

**Issue by blackChef** [vuejs/Discussion#218]
第一个问题：
elementDirective 跟 component 之间是什么区别？ 

第二个问题：
先 extend vue, 再用这个 constructor 去注册 component 的意义是这个 constructor 可以拿来注册多个 component 吗？有没有实际使用中的例子。

第三个问题：
component 注册之后必须依托某个父元素才可以使用，跟 knockout 那种扔进 html 就可以用的方式相比，不够方便。而且我注意到，直接用 `new Vue(..., { template: '' })` 也可以给元素添加 template，这里的 template 选项是为了什么设计的？因为直接用 `new Vue()` 的方式不需要父元素，为了能直接扔进 html 就能使用的效果，可能会针对它出现各种 hack，是不是太迷惑了。

**Comment by yyx990803** [comment]
1. component 是一个实例，有独立作用域，有自己的 data, methods, events 等等。elementDirective 本质上和普通的 directive 差不多，api 也一样，只是在模板里使用的形式不一样。
2. 直接 `Vue.component(Object)` 等价于 `Vue.component(Vue.extend(Object))`。只是想注册组件的情况下不需要手动 extend。
3. extend 出来的 constructor 可以和 Vue 本身一样 new。
    ``` js
    var Component = Vue.extend({ ... })
    new Component({ el: '#app' })
    ```
    另外，`new Vue()` 的意义和 angular 的 bootstrap, knockout 的 applyBindings() 差不多，就是启动编译。

**Comment by blackChef** [comment]
感谢回答。我就是看了英文文档才来问的。我不理解的是他们的使用场景，而不是他们返回了实例还是其他什么。
后两个问题已经想明白了，第一个还是不理解：
既然都是创造自定义组件的方法，什么时候使用 elementDirective，什么时候使用 component 是个迷惑我的点。component 看上去更直接易懂，能不能完全取代 elementDirective ？

**Comment by yyx990803** [comment]
大部分情况下你不需要使用 elementDirective。
elementDirective 适用的情况是：你想要 custom element 的语法，但是不希望创建一个组件实例。elementDirective 元素内部如何实现完全由你控制。
