### ISSUE TITLE
双向数据绑定问题

### ISSUE THREAD

**Issue by peijian708** [vuejs/Discussion#219]
用程序给绑定的input赋值，比如用jquery.val()，取不到更新后的值。
<input type="text" id="txtname" name="name" data-required="1" class="form-control" v-model="name"/>
$("#txtname").val("hgzp");
vm.name  还是原值

**Comment by yyx990803** [comment]
`v-model` 只侦听用户触发的事件，不侦听代码赋值。
而且既然用了 Vue 还用 jQuery 给 input 赋值的思路本来就是错误的。直接 `vm.name = "hgzp"` 就行了。
