### ISSUE TITLE
Browserify - Vue-Router - how to define prop callback to parent component. 

### ISSUE THREAD

**Issue by jishcem** [vuejs/Discussion#220]
I understand the way to set prop callback to parent component by defining the callback in the component template. 

But, I wonder, if there is the other way around for this ?

**Comment by yyx990803** [comment]
`<router-view callback="{{parentMethod}}"></router-view>`

**Comment by jishcem** [comment]
Thanks, I being dump with the structure,  was putting this callback in the wrong view file !
It works fine now.
