### ISSUE TITLE
Mustache 语法的问题

### ISSUE THREAD

**Issue by blackChef** [vuejs/Discussion#221]
今天在实验 component 的时候才知道通过 props 向 component 传值的时候，必须使用 `{{}}` 的形式，否则传进去的变量只会被认为是普通 string 。很合理，但是官方的手册上没有提到这点，很多人第一次用的时候可能都会出错。

现在的情况是这样：
- 在绝大部分的 directive 使用 vm 里的变量时，不使用 `{{}}`
- 在 `track-by`, `is`, `wait-for` 这些特殊的属性里不使用 `{{}}`
- 其他地方都是使用 `{{}}` 的形式

实际开发的时候，看到 `v-` 开头的属性，可以很明确的知道这是个 directive，不能往里面写 `{{}}`。看到其他属性的时候，就必须能分辨他们是 component 的 props 还是 track-by 那样的特殊属性。随着这些特殊属性越来越多，记住这些属性对开发者来说是个负担。
希望 vue 能在这方面优化下。对何时使用 mustache，何时不使用，给出明确的指导意见。

**Comment by yyx990803** [comment]
不管是什么属性，规则是：
1. 如果是 `v-` 开头，大部分情况下不能用 `{{}}`，除非是文档里明确指明的 "literal directive"
2. Literal directive 和任何其他属性都遵循以下规则：
  1. `{{}}` 外的视为字面量；
  2. `{{}}` 内的视为表达式。
