### ISSUE TITLE
v-model not working for select element

### ISSUE THREAD

**Issue by abhijitghogre** [vuejs/Discussion#222]
Here is the fiddle:

https://jsfiddle.net/08sunebu/

Expected output:
First select box should have option 1 selected (health) and second select box should have option 2 selected (tech).

**Comment by yyx990803** [comment]
You should be using the `options` param instead of `v-repeating` the options: http://vuejs.org/guide/forms.html#Dynamic_Select_Options

**Comment by abhijitghogre** [comment]
Ohhh damn how did I miss this!

Here is the working fiddle in case someone else faces the issue.

https://jsfiddle.net/08sunebu/1/

**Comment by abhijitghogre** [comment]
@yyx990803 May be get an inbuilt filter to convert an array of object compatible with select element.
