### ISSUE TITLE
I'm confused at first fixing in vue@0.12.5

### ISSUE THREAD

**Issue by butsalt** [vuejs/Discussion#228]
Fixed cases where templates that contain only `<content>`, `<component>`, `<partial>` or **a single component** are ignored silently. The first three cases will now turn the instance into a fragment instance and render correctly; **the last case will result in a warning**.

I don't understand the difference between `<component>` and `a single component`.
A single component means something like that? 
```javascript
template: '<component is="test"></component>'
```
[But that will not cause any warnings here. Try this fiddle.](http://jsfiddle.net/5sH6A/116/)

**Comment by yyx990803** [comment]
The phrasing may not be very clear. `<component>` means a dynamic component, the last case means a static component in the form of `<my-comp></my-cmp>`.

**Comment by butsalt** [comment]
Oh, so that's it! Thanks.
