### ISSUE TITLE
Is there any possibility that data will be deprecated in Component Options  in future?

### ISSUE THREAD

**Issue by butsalt** [vuejs/Discussion#229]
If it could be, I may not use `data` as default setting anymore when I define component in my current code.

**Comment by Nirazul** [comment]
I don't see that coming in the forseeable future. Data is the bread and butter for component data storage. Both `computed` and `props` storages have very distinctive tasks that differ from `data`.

**Comment by yyx990803** [comment]
No, I don't see a reason to do so.
