### ISSUE TITLE
Setting v-attr in beforeCompile

### ISSUE THREAD

**Issue by fenivana** [vuejs/Discussion#230]
I thought I can add v-attr data binding in beforeCompile phase, but it didn't work. Is there a Vue-way to approach this other than manipulating the template string?

```js
['alert', 'chat', 'close', 'logo-text', 'logo', 'star'].forEach(function(icon) {
  Vue.component('icon-' + icon, {
    template: require('!!raw!./icons/' + icon + '.svg'),
    props: ['width', 'height'],
    beforeCompile: function() {
      if (!this.width) {
        this.width = this.$el.viewBox.baseVal.width;
        this.height = this.$el.viewBox.baseVal.height;
      }
      this.$el.setAttribute('v-attr', 'width: width, height: height');
    }
  });
});
```

**Comment by yyx990803** [comment]
This has to do with some internal complexity when compiling instance root nodes. Manipulating the template string might just be the easy way here...

**Comment by fenivana** [comment]
Yeah, it's easy whatever way, just about my mysophobia  : )
