### ISSUE TITLE
`destroyed` hook doesn't work in case when `v-if` set to `false`

### ISSUE THREAD

**Issue by platov** [vuejs/Discussion#231]
There is the issue  - `destroyed` hook doesn't work

If component tag has `v-if` condition and `v-if` will set to false:
Expected result: component removed, `destroyed` hook called
Actual result: component removed, `destroyed` hook NOT called, although `beforeDestroy` hook is called normally

Probably this is a bug ?

jsfiddle demo: http://jsfiddle.net/g2o7a4c1/11/

**Comment by yyx990803** [comment]
Thanks, fixed as yyx990803/vue#1006.

**Comment by azamat-sharapov** [comment]
so it was bug indeed, Alexey :)
