### ISSUE TITLE
Vue.js 0.11 -> 0.12 升级指南 ？

### ISSUE THREAD

**Issue by BelinChung** [vuejs/Discussion#233]
通过 http://vuejs.org/2015/06/11/012-release/ 发现 0.11 -> 0.12 并未作太大的 API 或其他变更，是否按照该博文声明的几点变更即可顺利升级至  0.12 ？或还有其他未描述的细节变更？

**Comment by yyx990803** [comment]
全部改动参考 Release Notes 里面的 Breaking changes: 

https://github.com/yyx990803/vue/releases/tag/0.12.0
https://github.com/yyx990803/vue/releases/tag/0.12.1
https://github.com/yyx990803/vue/releases/tag/0.12.2

**Comment by BelinChung** [comment]
非常感谢
