### ISSUE TITLE
v-repeat, v-attr: img src and computed property

### ISSUE THREAD

**Issue by ThomasRalee** [vuejs/Discussion#234]
Hi guys,
I am trying to populate the image src through v-attr. But it is returning undefined if not empty instead of the actual img src. I have read through the documentation here but still cant really understand it...
http://vuejs.org/api/directives.html#v-attr

This is my front-end code. images is an array within my product object.  
'<' img v-repeat="images | filterBy '1' in 'profile'" v-attr="src:src"/ '>'
This is my script
data:{
		query:'',
		products:[],
	},

computed: {
	  src: function () {
           return 'img/products/' + this.imagePath;
	  }    
},

This must be a really simple problem for most of you. So please help me out! your help is deeply appreciated.

Thanks in advance!

**Comment by yyx990803** [comment]
Please create a live demo using jsfiddle or a similar service - it's very hard to debug problems by just looking at snippets.

**Comment by ThomasRalee** [comment]
Hi yyx990803,

I am sorry i cant really mirror my current application because its written through Laravel.
But i believe the codes is enough to illustrate what i am trying to do.  
http://plnkr.co/edit/W9UYEDlE5g2phAiaNAOQ?p=preview

Please help me, i am stuck with 404 error for quite some time now. 

Your help is much appreciated.

Thanks in advanced!

Cheers
Thomas

**Comment by appkr** [comment]
@yyx990803 
Hi? I think I have the same issue with the Laravel framework. 

Full version of issue description can be found at https://laracasts.com/discuss/channels/general-discussion/vuejs-and-curly-braces-in-scr?page=1#reply-90355 
<small>**`Note`** Both Laravel and Vuejs uses same mustache syntax for templating. @symbol in front of mustache means bypassing server side template compilation.</small>

I search through the documentation and the Internet, but I could not find the correct solution. 
Hope you see it once. 

Thanks.

**Comment by yyx990803** [comment]
@ThomasRalee you shouldn't be using a computed property here. The computed has its `this` context bound to the root instance, not the repeated one. You can just use an expression:

``` html
<img v-repeat="images | filterBy '1' in 'profile'" v-attr="src: 'img/products/' + imagePath">
```

If the asset path needs to be dynamic, you can use a filter instead of the computed property.

@appkr your problem is unrelated, but you should not be using mustache tags inside `v-attr`. It is already an expression.

**Comment by appkr** [comment]
@yyx990803 Thanks for the kind explanation. I solved the problem.
