### ISSUE TITLE
Do we need the DOM operation class library?

### ISSUE THREAD

**Issue by chaoren1641** [vuejs/Discussion#238]
In some scenarios, we need to operate some DOM, such as

```
$(".list li").removeClass('selected')
$(event.target).addClass('selected')，
```
Do you have a library of similar zepto in this case? Is there a more convenient method ？ 

：）

**Comment by yyx990803** [comment]
There's the internal `Vue.util.addClass(el, className)` and `Vue.util.removeClass(el, className)`. However in most cases you should use `v-class` instead.

**Comment by chaoren1641** [comment]
I understand, thank you very much .
