### ISSUE TITLE
v-model doesn't support input type="file"

### ISSUE THREAD

**Issue by airtoxin** [vuejs/Discussion#24]
I tried to get file name using v-model directive, but it did not work.
http://jsfiddle.net/4PTjF/

I think, determination of listining event in directive's model.js needs more condition.

``` javascript
self.event =
    (self.compiler.options.lazy ||
    tag === 'SELECT' ||
    type === 'checkbox' || type === 'radio' || type === 'file')
        ? 'change'
        : 'input'
```

or is there a better way to get file name?

**Comment by 8lbiasian** [comment]
so is it still not supported ?? 
how to deal with input file then ??

**Comment by TeroBlaZe** [comment]
We need it

**Comment by adam12** [comment]
> We need it

I'm currently using this as a directive. Appears to work OK.

```javascript
module.exports = {
  handleChange: function(e) {
    this.vm.$set(this.expression, e.target.files[0]);
  },

  bind: function() {
    this.el.addEventListener('change', this.handleChange.bind(this), false);
  },

  unbind: function() {
    this.el.removeEventListener('change', this.handleChange, false);
  }
}
```

**Comment by TeroBlaZe** [comment]
@adam12 I've got a better solution
```javascript
<input v-el="avatar" type="file" name="avatar" id="avatar" v-on="change:upload">
    methods: {
        upload: function(e) {
            e.preventDefault()
            var files = this.$$.avatar.files
            var data = new FormData()
            // for single file
            data.append('avatar', files[0]);
           // Or for multiple files you can also do
           //  _.each(files, function(value, key){
           //      data.append(key, value);
           // });
           // But the luck of it that it returns an array without named index e.g. ['avatars' => [0,1,2]] but [0,1,2] instead and I don't know how to fix it
            this.$http.post('/avatars/upload', data, function (data, status, request) {
                  //handling
            }).error(function (data, status, request) {
                 //handling
            });
        }
```

**Comment by TeroBlaZe** [comment]
yay I did it! Not trivial huh
```javascript
           _.each(files, function(v, k){
                data.append('avatars['+k+']', v)
            })
```

**Comment by pavliha** [comment]
@TeroBlaZe, thanks

**Comment by danielchou** [comment]
@TeroBlaZe 
You did a great help for me, thanks.

**Comment by pnkjsuthar** [comment]
// Or for multiple files you can also do
             _.each(files, function(v, k){
            //    data.append('avatars['+k+']', v);
           });

for multiple file upload  i am using above code. but it shows error ('_ is undefined'). What should i do for multiple file upload. Please suggest any idea.

**Comment by pnkjsuthar** [comment]
For multiple file upload you can use this.
/*
 * for multiple uploads
 * 
/
var files = this.$$.moreImage.files;
for(var key in files){
          formData.append('more_image['+key+']', files[key]);
  }

//in your controller you can do like this
foreach(Input::get(more_image) as $image){
     //wirte your code here
}

**Comment by aaronranard** [comment]
Is there a solution for this for Vue 1.0? v-el no longer exists.

**Comment by azamat-sharapov** [comment]
http://vuejs.org/api/#v-el

**Comment by aaronranard** [comment]
Right. Searched for it and couldn't find it. Thanks.

**Comment by frthjf** [comment]
Thanks for @TeroBlaZe solution! A quick note for Laravel users though: Sending the FormData object in a PUT/PATCH request did not work for me in Laravel 5.3. A simple workaround is to use a POST request instead but instruct Laravel to consider it as a PUT request by adding the following line to the upload method: `data.append('_method', 'PATCH')`

**Comment by tobz-nz** [comment]
@rafaelrinaldi I think the value should be `file.name`, as a bunch of browsers including: IE, Chrome & Safari; prepend the `file.path` with `c:\fakepath` (regardless of the user's platform).

**Comment by murbanowicz** [comment]
How to find workaround when `<input>` is under `v-if` so it can't use `v-el` .. ?

**Comment by andreaselia** [comment]
@murbanowicz `refs` is a good alternative to `v-el` https://vuejs.org/v2/api/#vm-refs

**Comment by 4096void** [comment]
@AndreasElia  But refs is not reactive enough to being used in computed or methods, it still some tweak to achieve goals, I'm using Vue & related open issue 2.x https://github.com/vuejs/vue/issues/3842

**Comment by eliyas5044** [comment]
For `vue 2.x` it should like this:
```
<input ref="image" type="file" @change="onFileChange">
```
```
onFileChange() {
    const files = this.$refs.image.files;
    const data = new FormData();
    data.append('logo', files[0]);
}
```

**Comment by andreaselia** [comment]
@eliyas5044 `var` would be more appropriate as the variable doesn't change.
