### ISSUE TITLE
How to deal with props name like "data-*" if hyphenated prop names been deprecated?

### ISSUE THREAD

**Issue by butsalt** [vuejs/Discussion#248]
I'm commonly using props start with `data-`. `data-*` is recommended to exchange proprietary information. I don't need to worry about the attribute that I use to exchange data will effect dom.
```JavaScript
props: {
    "data-checked": {
        type: Boolean
    }
}
```
If hyphenated prop names have been deprecated, I wish I can use props start with 'data-' like this in future:
```HTML
<my-component data-checked></my-component>
```
```JavaScript
props: {
    "checked": Boolean
}
this.checked //true
```
And
```HTML
<my-component data-my-msg="some thing"></my-component>
```
```JavaScript
props: {
    "myMsg": String
}
this.myMsg //"some thing"
```
If not find properer attribute, then
```HTML
<my-component my-msg="some thing"></my-component>
```
```JavaScript
props: {
    "myMsg": String
}
this.myMsg //"some thing"
```

**Comment by yyx990803** [comment]
Yeah, sounds like a good idea. You should move this to the main repo.

**Comment by butsalt** [comment]
Great! By the way, I truly hope I could come to Shen JS to see you. But that's too far for me.  I'm really one of your big fan!:laughing::laughing:

**Comment by yyx990803** [comment]
@butsalt thanks! :)

**Comment by azamat-sharapov** [comment]
Shen JS? is this meetup? where is it?!

**Comment by yyx990803** [comment]
@azamat-sharapov haha it's in China: http://2015.jsconf.cn/

**Comment by azamat-sharapov** [comment]
ah can't make it :disappointed: You should make it in other asian countries also, like Thailand, etc. :smile: I'm sure you have many fans, not only me and @butsalt :wink:

**Comment by azamat-sharapov** [comment]
Going little off topic here, but just one question: was this conf recorded and be posted online somewhere?

**Comment by yyx990803** [comment]
It's recorded, but I don't know when they will upload it. Probably takes a few days.

**Comment by azamat-sharapov** [comment]
Great! See you soon then :smile:

**Comment by bjtqti** [comment]
fans ? count me in .
