### ISSUE TITLE
Guidelines for Translation

### ISSUE THREAD

**Issue by VitorArjol** [vuejs/Discussion#250]
Hi @yyx990803 :D I was thinking about provide the Brazilian Portuguese translation for Vue.js (if you have interest on that type of contribution). Is there a guideline about how to do it? 
I saw the lang-zh branch, but I don't know if this is the right way to do it.

\o

**Comment by yyx990803** [comment]
You can take a look at the Japanese fork: https://github.com/vuejs-jp/vuejs.org

Maybe @kazupon could offer more suggestions in how to maintain a translation fork.

**Comment by VitorArjol** [comment]
I'll talk to him :+1:

**Comment by kazupon** [comment]
@VitorArjol 

We did not have the guidelines for translation, but we did translated the following such workflow.
I hope you find our workflow informative.

- create organization for translation: ex) https://github.com/vuejs-jp
- fork from https://github.com/vuejs/vuejs.org to https://github.com/vuejs-jp/vuejs.org
- invite translation contributer to translation organization
- create topic branch on organization/vuejs.org for translation: ex) lang-ja
- assign translation section: ex) source/guide/installation.md -> kazupon
- each contributer fork from https://github.com/vuejs-jp/vuejs.org: ex) https://github.com/kazupon/vuejs.org
- create topic brand on forked translation repository for translation working: ex) translation/guide/installation
- if finish translation, push to the branch: ex) git push origin translation/guide/installation
- submit a pull request to `lang-xx` branch of organazation/vuejs.org
- review a pull request
- merge a pull request to `lang-xx`

**Comment by VitorArjol** [comment]
@kazupon This is great!

I'll start the translation. Thank you!
