### ISSUE TITLE
Recommended way of integrating flux with vue

### ISSUE THREAD

**Issue by yang-wei** [vuejs/Discussion#251]
First of all thanks for this awesome library. It helps us build app quickly and fun but app grows. So I was trying to find a way to scale and I saw flux in the [Tips & Best Practices section](http://vuejs.org/guide/best-practices.html#Communication_Between_Instances) in docs.

So I was trying the approach it similar to this [fiddle](http://jsfiddle.net/yyx990803/hte7vwvx/) and my output is something like [this](https://github.com/yang-wei/vue-flux).

Two things, 

1.In the both examples above, Vue are used to handle event and render output. React has diffing algorithms to decide which view to be updated but when it comes to Vue, it only rerender the view. So what's the best practices of updating view with Vue.js (is using track-by in this case will improve perfomance).

2.I was trying to use Vue instance as a store so that it can leverage Vue event system
```js
var ItemStore = new Vue({
  data: { items: [] },
  methods: { } ...
})
```
but I think it get too much, a basic object is just what a store need.  Is there a way to extends Vue.js event system for my store so that I can do something like this.
 ```js
   class ItemStore extends Vue.Events {
       // code
   }
 ```
Then I can throw away another dependency.

**Comment by yyx990803** [comment]
1. Proper `track-by` hints are all you need for efficient re-renders (no DOM is trashed/recreated).

2. It's actually possible to just use a plain container for Vue data:

  ``` js
  class ItemStore {
    constructor (data) {
      this.data = data || { count: 0 }
    }
    increment () {
      this.data.count++
    }
  }

  // in Vue components
  new Vue({
    // when you pass it into a Vue instance here,
    // ItemStore.data becomes reactive
    data: ItemStore.data
  })
  ```

**Comment by yang-wei** [comment]
thanks so much !

**Comment by yang-wei** [comment]
> This means you should never modify the reference to that object on both sides.

Not quite understanding this. Do you mean that we should only modify data on either side ?

**Comment by yyx990803** [comment]
Yeah, you're not supposed to do `store.data = somethingElse` or `vm.$data = somethingElse`, because `store.data === vm.$data` and this object is what keeps things in sync. Mutate that object, but don't lose reference to it.
