### ISSUE TITLE
Removing Diacritics on filterBy method

### ISSUE THREAD

**Issue by vitorarjol** [vuejs/Discussion#257]
Today I was working on a table in my system, and I noticed that search results were not displayed as I expected. The problem was involving the use of the filterBy function and the diacritcs (in my case, accents like á,é, ô(etc) and the use of ç (these are widely used in portuguese)).

I solved this issue by creating a custom filter which replaced these characters on the search.
Is there another workaround on that? Moreover, someone else has this kind of problem? I can work on a PR for that.

Regards

**Comment by simplesmiler** [comment]
Custom filter looks like a proper solution to me.
I don't think this belongs to core, but having this as a plugin would be nice.

**Comment by VitorArjol** [comment]
Thanks @simplesmiler for the feedback. I agree with you about a plugin :+1:

**Comment by azamat-sharapov** [comment]
Can we say "filterBy doesn't support UTF" here? or it's wrong terminology?

**Comment by VitorArjol** [comment]
Actually I think that filterBy supports UTF. My problem was that the filterBy method considers á != a, and I need to allow my users search some name like "Lia" and get results like "Liá" and "Lia".
I need an accent insensitive comparison.

**Comment by azamat-sharapov** [comment]
Oh I see now. Other than creating custom `filterBy`, you probably could also create one more small filter, which substitutes those characters and then passes to `filterBy`.

**Comment by VitorArjol** [comment]
Hm, I'll work on that later today. Just a simple question: How could I call `filterBy` on that situation (outside of an html file)?

Thanks for the discussion!

**Comment by azamat-sharapov** [comment]
I meant piping like so: `v-repeat="items | convertDiacritics | filterBy searchKey"`. There is also another easy way: having searchKey as computed prop: http://jsfiddle.net/fc4a3rjb/ 
One problem here though - it can't return both `a` and `á` for results. So it's probably best to `convertDiacritics` in array and then pass (pipe) to `filterBy`.

**Comment by simplesmiler** [comment]
@VitorArjol you could actually go further and implement [phonetic search](https://en.wikipedia.org/wiki/Phonetic_algorithm). That would be very useful!

Regarding calling `filterBy` from custom filter:
```js
var filterBy = Vue.filter('filterBy');
return filterBy(arr, search, delimiter, dataKey);
```

But it's probably better to use piping, as suggested by @azamat-sharapov.

**Comment by vitorarjol** [comment]
I'm refactoring my front end now, when I get to this part I'll update here.

**Comment by iskrisis** [comment]
I would like to know how to solve this. I can remove diacritics the searchTerm but then when somebody will start to write with diacritics it will give him nothing. I need both to be true.

@vitorarjol how did you solve this? Thanks?
