### ISSUE TITLE
Directive to parse data attributes

### ISSUE THREAD

**Issue by rafaelrinaldi** [vuejs/Discussion#27]
I use data attributes sometimes and it would be really helpful to have a directive that parse them and compute to `$data`. `v-data`, maybe?

```html
<main id="app" data-foo="bar">My Application</main>
```

```js
new Vue({
  el: '#app',
  ready: function() {
    console.log('Vue is awesome »', this.foo); // bar
  }
});
```

What do you guys think?

`/ping` @yyx990803

**Comment by FWSimon** [comment]
Does it work :)?

**Comment by rafaelrinaldi** [comment]
@FWSimon With [`data`](http://vuejs.org/api/#data) and [`props`](http://vuejs.org/api/#props) this isn't needed at all :smiley: Just use an object literal as your component settings and you should be good to go. If you still want to use `data-*` you can write a custom [computed property](http://vuejs.org/api/#computed) :+1: 

I'm closing this issue.

**Comment by tebaly** [comment]
How it work with simlpe Vue instans(not Vue.component to simplify) like
```
var element = new Vue({
    el: '#element',
    props: ['number'],
    mounted: function () {
        console.log(this.number);
    },
    methods: {
        show: function () {
            console.log(this.number);
        },
    }
});
```
In html page
`<span id="element" number="2" @click="show">0</span>`

> undefined
> undefined
