### ISSUE TITLE
Possible bug in Dragonball

### ISSUE THREAD

**Issue by swift1** [vuejs/Discussion#277]
When removing the div elements surrounding a component inside a template, the script won't work.

Example:
This one works: http://jsfiddle.net/1tv62ohp/4/
````javascript
<script id="parent-template" type="text/x-template">
    <div>
        <child-component msg="{{msgFromParent}}"></child-component>
    </div>
</script>
````
This one fails, but gives no errors: http://jsfiddle.net/1tv62ohp/5/
````javascript
<script id="parent-template" type="text/x-template">

        <child-component msg="{{msgFromParent}}"></child-component>

</script>
````

**Comment by butsalt** [comment]
In second case, `child-component` is regarded as root element of parent-component. And `component` directive will not work for component's root element( actually there are many directives will not work for component's root element ). It means component transform will not happen in this case. But `props` directive will sill work. 
![image](https://cloud.githubusercontent.com/assets/8847427/8714101/c507a3fc-2ba3-11e5-92a5-c384850f906e.png)
That might be a bug. Personally, I always  set a real root element for my component to aviod strange things happen as [Vue's developer said](http://vuejs.org/guide/best-practices.html#Fragment_Instance)

**Comment by swift1** [comment]
Thanks for your answer. This is typically an issue that when you read about it in the documentation the first time, you forget about it, and then you only really learn how it works when you've made the mistake and re-read the documentation. :)
