### ISSUE TITLE
组件与组件之间如何传递数据？

### ISSUE THREAD

**Issue by chaoren1641** [vuejs/Discussion#284]
按照[Hacker News](https://github.com/yyx990803/vue-hackernews)源码架构创建的vue项目，现在有这样一个需求，当A页面跳转到B页面时，B页面做了一些数据操作，这时候点击返回或浏览器后退按钮，A页面model要发生改变（或者说在B页面就改动A页面的model，使得A页面能自动更新），目前想到的解决方案是使用window全局变量，或者localStorage来做数据传递，但这样好像失去MVVM的意义了，VUE有提供好的方法吗？

交互有些复杂，暂时没有提供demo，不好意思啦～～

**Comment by ppq1991** [comment]
其实我觉得用 localStorage 或者 sessionStorage 也挺好，可以避免用户刷新页面丢失当前状态。
而且就算用全局变量的话也不应该用window，应该用个闭包内全局变量，比如用browserify打包。
如果他们有父级vm的话我觉得还可以把状态放在父级vm里，用$dispatch和$broadcast通信。

我最近做一个Web App也有类似的需求，A页跳到搜索页，选取一个搜索条件后返回A页，A页需要用刚刚选取的搜索条件，我是放在 sessionStorage 里，感觉用起来还挺方便，而且不怕用户刷新页面。

**Comment by moJiXiang** [comment]
我也有类似的需求。
登录页面和app-header页面为两个组件，我在登录页面调用接口返回一个user数据，然后需要在app-header中显示出user的name等信息。
根据两位的意思，只能用localStorage活着sessionStorage了。

**Comment by chaoren1641** [comment]
@moJiXiang 其实Vue提供了比较方便的组件引用方法，比如你登录页面引用了app-header组件，你可以这样做：
```vue
<app-header v-ref="header"></app-header>
```
然后在登录页面中：
```javascript
this.$.header.user.name = 'text';
```
同理，如果需要调用父组件中的其它组件可以用`this.$parent.$.id`

**Comment by liupei2012** [comment]
vueX 是否能解决路由跳转后页面与页面之间的数据通信
