### ISSUE TITLE
大家帮忙看下这个地图组件应该怎么做

### ISSUE THREAD

**Issue by liyunfang** [vuejs/Discussion#285]
我要做一个百度地图的组件component
要在组件里实例化百度地图，然后把百度地图对象保存到data里，外部要调用。

我现在这样做了：
在组件的初始化事件里 实例化地图对象后   
this.$add('_bmap',map); 加下划线是为了不重写这个对象

外部调用的时候 在组件上加个 v-ref="bdmap"
vm.$.bdmap.$data._bmap.centerAndZoom(new BMap.Point(116.417854,39.921988),15);
vm.$.bdmap.其他方法
这样做的功能没有问题， 只不过每次调用完方法 会返回一个undefined有点不理解

**Comment by liyunfang** [comment]
我感觉应该提供一个属性    就是存放对象用的，不用双向绑定，而且父级也可以访问到。

**Comment by butsalt** [comment]
如果我来做的话，我不会把这个组件的map暴露出来。这个组件在创建的时候应该需要海拔以及中心点两个参数。然后组件监听海拔及中心点的数据变化，一旦发生变化，组件内部调用map的centerAndZoom进行地理位置重置。

**Comment by liyunfang** [comment]
@butsalt  功能比较复杂有计算路线的功能不光是展示

**Comment by butsalt** [comment]
如果你把map暴露出来，你还需要Vue为你做什么呢？

**Comment by liyunfang** [comment]
@butsalt  就是为了做一个地图的组件啊 用到的地方直接用 一个页面可能会有多个地图   
或者是我想错了，不应该用Vue做地图组件

**Comment by butsalt** [comment]
Vue的主要意图就是以数据做驱动的，如果要用Vue来做你的地图组件的话。外部应该传入一个足够描述地图样子的数据就够了，当数据发生变化的时候地图会做出对应的变化。你或许可以在你的地图组件下再新增多个子组件用来负责某种特定的展示。

**Comment by liyunfang** [comment]
@butsalt   谢谢你的回答，现在没搞明白。

**Comment by ppq1991** [comment]
@liyunfang  我觉得你目前的需求，好像没必要用Vue来做这个组件呢。
