### ISSUE TITLE
vuejs 下拉刷新问题/Pull-down refresh use masonry question

### ISSUE THREAD

**Issue by nolouch** [vuejs/Discussion#286]
我用vuejs来做下拉刷新，数据通过ajax获取，获取好通过
```
//触发下拉刷新
$ajax(){
     vm.weibos.push( results)
}
```
数据更新后视图是加载在前面，怎样才能加载到已生成视图的后面去？？
我是参考这个案列写的   [Firebase + 验证](http://jsfiddle.net/yyx990803/2ok0hp6c/light/)

##补充

刚刚发现了原因，是masonry的插件是的新生成的试图浮在旧试图上面，必须是masonry.destory()销毁之后重新生成试图才正常，但是masonry重新生成会是下拉条定位到最上面，不知道怎么实现masonry的[appended()](http://masonry.desandro.com/methods.html#appended)的效果，大家有没有什么好的办法?

#################################################################################
I use vuejs to do Pull-down refresh，and fetch data from ajax，like
```
$ajax(){
     vm.weibos.push( results)
    $('grid-item').masonry('destroy')
    refreshMasonry()
}
```
when the data update，the masonry should destroy and refresh then the data will load,but the scroll will up to top,if masonry not destroy, the new  view will cover the old view.I wann't achive that effect like masonry [appended()](http://masonry.desandro.com/methods.html#appended)，and how should i do?

**Comment by swift1** [comment]
How do you expect people to help you if you ask the question in chinese/japanese? You only want help from asian people? :frog:

**Comment by nolouch** [comment]
@swift1  I'm sorry and i update the question.

**Comment by swift1** [comment]
If you upload an example on jsfiddle.net then it's much easier for people to try to help you.
