### ISSUE TITLE
Trouble with $watch

### ISSUE THREAD

**Issue by swift1** [vuejs/Discussion#287]
Hi guys. I'm trying to watch for changes to a property inside a component with $watch, but I can't get it to work.

Error: Uncaught TypeError: t.trim is not a function.

Does anyone know why this doesn't work?

````javascript
Vue.component("my-component", {
	template: "test",
	
	data: function() {
		return {
			percent: -2
		}
	},
	created: function() {

		this.$watch(this.percent, function (newVal, oldVal) {
			
			console.log(newVal + ',' + oldVal);
		});
	}
});
````

***EDIT:*** Never mind guys, I figured it out! :smile:  I had to use 
````javascript
this.$watch(function(){ return this.percent; }, function (newVal, oldVal) {
````
instead of:
````javascript
this.$watch(this.percent, function (newVal, oldVal) {
````

**Comment by yyx990803** [comment]
Actually, `$watch` takes a string by default: `this.$watch('percent', ...)`

**Comment by swift1** [comment]
Ok, that explains why I got the error "Uncaught TypeError: t.trim is not a function" (since 'percent' is an integer and not a string).

However, I still need to use a function to get the watcher to work (maybe because the watcher is inside of a component?).

This doesn't work (but gives no errors):
````javascript
this.$watch((this.percentLow+''), function (newVal, oldVal) {
````

This works:
````javascript
this.$watch(function(){ return this.percentLow }, function (newVal, oldVal) {
````

**Comment by yyx990803** [comment]
I think you are misunderstanding how string conversions work in JavaScript...

**Comment by swift1** [comment]
I know how they work. I used ````javascript + '' ```` to convert the integer property to a string, since the $watch function takes a string as a parameter. That way, I got no errors in the console, but the watcher did not get registered properly. I can upload a fiddle of it tomorrow so I can show you what I mean.

**Comment by yyx990803** [comment]
`$watch` takes a string, which should be **the path of the property that you want to watch**. Passing in `"3"` doesn't make sense.

**Comment by swift1** [comment]
You're right, this.percent is of course a number and not a path. Sometimes when you look at code for too many hours straight, you start to make stupid mistakes. :smile_cat: 

But I guess I got confused because passing in a function that returned a number (and not a string with a path), still worked.

Example:
http://jsfiddle.net/wctqovpe/

**Comment by yyx990803** [comment]
Passing in a function is a supported way of using `$watch`: http://vuejs.org/api/instance-methods.html#vm-\$watch\(_expOrFn\,_callback\,_\[options\]_\)
