### ISSUE TITLE
props in dynamic components

### ISSUE THREAD

**Issue by PavelPolyakov** [vuejs/Discussion#291]
Hi,

Again I'm fighting with the dynamic declaration.

My current attempt is the next.

1. In the template I have this:
```html
        <div class="modalContainer" verbs="{{verbs}}"></div>
```

2. In the code I have this:
```javascript
var addVerbModal = Vue.extend(require('./add-verb-modal.vue'));

var modal = new addVerbModal({
                    props: {
                        verbs:{
                            type: Array
                        }
                    },
                    el: '.modalContainer'
                });
```

3. In the child component I have this:
```javascript
ready  : function () {

            var self = this;

            console.log('this', this);

            console.log('verbs 2', this.verbs);
            //console.log('par 2', this.$parent.verbs);

            // remove the instance, after it would be hidden
            $('#addVerbModal').on('hidden.bs.modal', function (e) {
                self.$destroy(true);
            });

            $('#addVerbModal').modal('show');
        }
```

And, at the end, I have this in my browser:
![image](https://cloud.githubusercontent.com/assets/839290/8767518/e3383080-2e5f-11e5-8635-510a329f3866.png)

Which means that ```verbs``` were not passed, for some reason, and I have ```undefined``` instead of Array.

Whyyyy? :) (tried the same with this.$addChild - the verbs are not there as well, however I can use ```this.$parent.verbs``` in this case)

Here is the full source of the file:
https://github.com/PavelPolyakov/twiliocms/blob/feature/inline-template/public/app/components/response.vue

@yyx990803 
Please, help me to find a way to use realtime components.
I have tried three different ways:
https://github.com/vuejs/Discussion/issues/254#issuecomment-122659066
https://github.com/vuejs/vueify/issues/15

and the current one. Nothing is 100% working, I'm a bit sad.

**Comment by yyx990803** [comment]
I've said somewhere else that you should just use a `v-if` on the modal. That is the idiomatic way to dynamically toggle a component in Vue. But you insisted going the harder way without fully understanding how the internals work...

**Comment by PavelPolyakov** [comment]
@yyx990803 
Correct, but I don't want to use the flag.

All the ways that I'm trying to use are logical, not something which I try to get out of the blue. Everything I'm trying to use comes from the documentation in this or the other way and I don't see the reasons why it doesn't work.

I appreciate your work and framework in particular, it looks like a great tool, don't get me wrong, please. But for me - frameworks are the bricks provider, and I want to build my solution using these bricks, the smaller the bricks are the better the framework is. And this ```v-if``` brick looks for me quite big :)

Ok, let's go the ```v-if``` way. I have an issue there.

1. I put this to the template:
```
<div class="modalContainer" verbs="{{verbs}}" v-if="showModal"></div>
```
2. I put this to the parent component ```ready``` method:
```javascript
var modal = new addVerbModal({
                props: {
                    verbs:{
                        type: Array
                    }
                },
                el: '.modalContainer'
            });
```
also tried to add this as ```components``` object of the "parent" component:
```
modal : new addVerbModal({
                props: {
                    verbs:{
                        type: Array
                    }
                },
                el: '.modalContainer'
            })
```
3. I set the flag from the method:
```javascript
showAddVerbModal: function () {
                this.showModal = true;
}
```

However, the only thing that happens is the display of the initial template part.
![image](https://cloud.githubusercontent.com/assets/839290/8767686/da9025d2-2e64-11e5-9414-b7c666c968c1.png)

When should I call the ```new Component``` so it would be mounted to the newly appeared html automatically? 

Full code of the attempt:
https://github.com/PavelPolyakov/twiliocms/blob/feature/inline-template-2/public/app/components/response.vue

**Comment by PavelPolyakov** [comment]
@yyx990803 

Here is the jsbin:
http://jsbin.com/lakigoquji/edit?html,js,output

**Comment by yyx990803** [comment]
Now, when you are using `v-if`, if needs to be a component, so you need to:

1. register the modal component with a name, e.g. `modal`, inside the response component:

  ``` js
  components: {
    modal: require('./add-verb-modal.vue')
  }
  ```

2. Use the component syntax instead of a plain div:

  ``` html
  <modal verbs="{{verbs}}" v-if="showModal"></modal>
  ```

It seems to me you just didn't read through the docs carefully enough to understand these details, and you really should be doing that instead of 1. making "trial and error" attempts hoping it will somehow work; 2. opening issues about the same problem over and over again. Also, when you are using a the lower-level, imperative API, there are even more things that can possibly go wrong with your usage because it requires some level of knowledge of how Vue internals work.

I didn't respond to some of your questions because you are often trying to use an API without fully understanding it, and a lot of the usage issues could be solved by simply reading the docs more carefully. Let's be honest - I don't have the time to hold your hands and walk through every little detail when there are bugs and features to work on, and when the answers can already be found in the docs. Please be considerate of a maintainer's time when you are opening issues like this (and mentioning me every time).

**Comment by PavelPolyakov** [comment]
@yyx990803 
I understand your point and appreciate it, however it seems that currently you are the only person who can give a response.

Sorry for a lot of issues, but I have read the docs for sure, maybe not gathered a full picture yet. Indeed I haven't checked the source code of the framework, but I still think that my issues and attempts are following the documentation logic.

Thanks,

**Comment by azamat-sharapov** [comment]
так чем не устраивает `v-if`? Это не совсем "flag". `v-show` - да, он flag, потому что просто скрывает элемент с помощью CSS. А `v-if` это совсем другое - он не пихает блок элемента, пока данный ему аргумент не "truthy". Если он "falsey", то элемент вообще в DOM не появится, будет хранится в переменной Javascript. Мне кажется ваш метод в конце концов ничем не отличается - тот модал будет также храниться в переменной JS.

**Comment by PavelPolyakov** [comment]
@azamat-sharapov 
под флагом я имел в виду необходимость выставлять флаг в самом компоненте (показывать/ не показывать сабкомпонент).

В принципе сейчас уже устраивает, однако, такой случай, например, http://jsbin.com/baberovixi/1/edit?html,js,output - работает не верно. Хотя, согласно документации должен работать. Из моего опыта в итоге - единственное что работает это hash map ```components``` :)

и в целом, такой подход не позволяет динамически формировать строки "компонентов", т.е. я не могу сформировать динамически компонент и передать ему N property и потом скомпилировать, я должен сперва захардкодить это в шаблон. На мой взгляд это делает процесс менее абстрактным. Либо, как я увидел из другого примера, это провоцирует работать с дочерними компонентами через ```this.$parent``` или через события.

**Comment by simplesmiler** [comment]
@PavelPolyakov раз нужен полиморфизм (строки компонентов), то у компонентов должен быть одинаковый интерфейс. Так почему бы не хранить в data пары `<компонент, аргументы>`, а в шаблоне сделать v-repeat по ним?

**Comment by PavelPolyakov** [comment]
@simplesmiler 
Если у компонентов одинаковый интерфейс (они принимают одинаковые ```props``` всегда, то проблемы опять же нет), но почему они должны принимать одинаковые ```props``` ?

Что если проперти разные?

Допустим, у меня есть компонент А, который не знает какой компонент он будет показывать в будущем. Он делает запрос на сервер, сервер ему говорит - покажи компонент B, он принимает эти проперти (a1,a2,a3) , т.е. выглядит вот так:
```
< component is="b" a1={{a1}} a2={{a2}} a3={{a3}}></component>
```

Компонент A должен его зарендерить и прокинуть в него все проперти.
В момент прорисовки компонента A, мы не знаем какие компоненты он будет рендерить внутри себя.

Разве это не выглядит как реальная задача?
Как быть?

**Comment by simplesmiler** [comment]
@PavelPolyakov если хочется полиморфизм, то у компонентов **должен** быть одинаковый интерфейс. Если у них интерфейс разный — нужны адаптеры, которые будут приводить интерфейс к одинаковому.

Пример: https://jsfiddle.net/simplesmiler/v6w8tzae/1/ (в продакшене так делать не стоит).

**Comment by PavelPolyakov** [comment]
@simplesmiler 
Спасибо за мысль, в принципе понял, на практике в примере пока ошибка
![image](https://cloud.githubusercontent.com/assets/839290/8776656/1ef7fef0-2ef3-11e5-9e33-760ea9b25735.png)

**Comment by PavelPolyakov** [comment]
@simplesmiler @azamat-sharapov 
Друзья, я подскажите мне плз следующее.

У меня есть компонент с v-if, выглядящий так:
```
<component is="addVerbModal" verbs="{{verbs}}"  v-if="showModal"></component>
```

Когда ```showModal```  выставляется, то компонент рендерится, на его ```ready``` я показываю модальное окно.

Но, я хочу сделать так, что когда я закрываю окно - компонент полностью удалялся и все возвращалось на круги своя. т.е. вместо него появлялась бы заглушка с ```v-if```.

Удалить компонент просто:
```
$('#addVerbModal').on('hidden.bs.modal', function (e) {
                self.showModal = false;
                self.$destroy(true);
            });
```

Но как я могу поставить обратно
```
<component is="addVerbModal" verbs="{{verbs}}"  v-if="showModal"></component>
```

??

Либо как мне быть?

Спасибо за советы,

**Comment by simplesmiler** [comment]
@PavelPolyakov я не очень понял. Переменная `showModal` ведь в таком случае принадлежит не самому компоненту, а его родителю. А зачем разрушать родитель?

Обычно вручную вызывать `$destroy` не нужно. Если окна создаются через `v-repeat`, то он сам разрушит инстансы при `$remove` соответствующего поля из `data` родителя. Если окно создается через `v-if`, то оно само разрушится при установлении этой переменной в falsey-значение.

Пример: https://jsfiddle.net/simplesmiler/mv6hbLrz/

**Comment by PavelPolyakov** [comment]
@simplesmiler 
Ваш пример у меня опять не работает, но спасибо за помощь.
Действительно действий дополнительных предпринимать не нужно.

Я был смущен что html элемент полностью пропадал из DOM и думал что он не вернется, однако он стал возвращаться :)
