### ISSUE TITLE
How to convert the object of Vue to normal object？

### ISSUE THREAD

**Issue by chaoren1641** [vuejs/Discussion#292]
In the debug, we can see the contents of the object being treated with get and Vue by `vm.log ('key')`. If I need to merge a bunch of data and other normal javascript object, which is passed to other components, how does it need to be converted?

**Comment by yyx990803** [comment]
If you are just passing it to another component, there is no need to convert it back to a normal object; If you want to make a copy before passing in, you can just `JSON.parse(JSON.stringify(obj))`.

**Comment by chaoren1641** [comment]
Has been resolved,Thanks.

**Comment by vedmant** [comment]
@yyx990803 It would be nice to have something like toJSON() method for this

**Comment by yf-hk** [comment]
+1 for toJSON() method. Sails.js has got something similar for its ORM and I found it quite handy

**Comment by imbolc** [comment]
Why not `Object.assign({}, vueObj)`?

**Comment by vedmant** [comment]
@imbolc It's just easier to read, `JSON.parse(JSON.stringify(vm.$data))` can be used the same way, the point is to have clear and easy readable code.

**Comment by gluons** [comment]
Does `JSON.parse(JSON.stringify(obj))` work with the object that have `RegExp` or `Function`?

**Comment by f3l1x** [comment]
So `JSON.parse(JSON.stringify(vm.$data))` is the best approach?

**Comment by MattCCC** [comment]
Seems it's the only one, but doesn't look good anyway. Object.assign didn't work in my case.

```
/*
  Convert vue object
*/
global.getVueObject = obj => {
  return JSON.parse(JSON.stringify( obj ));
};
```

My usage:

`let it_be_normal_object = getVueObject(your_object);`

**Comment by jpokrzyk** [comment]
```javascript
const newObj = { ...vueObj }
```

**Comment by f3l1x** [comment]
Oh, how cool. @jpokrzyk

**Comment by shanemgrey** [comment]
The solution by @jpokrzyk seems about as elegant as it can get.  The spread operator is a wonderful shortcut.  And using const seems needed to cause javascript to resolve the value of the object in cases where it's an observer.  

This solved hours of frustration for me with vuex when I thought Object.assign was the accepted method of cloning a state(using a getter) to a local.  Turns out it just cloned the observable.  

That caused vuex strict mode to complain 'Do not mutate vuex store state outside mutation handlers'

I'm adding this here because, even though it's an old closed issue, it still comes up as a top hit for how I was searching the issue.  Hopefully others will find the same resolution thanks to the added keywords.

**Comment by warent** [comment]
A very strange thing happens with a watcher though. For example:
```
for (let k in store.state) {
  store.watch(state => state[k], (value) => {
    console.log(JSON.parse(JSON.stringify(store.state[k]));
    console.log(store.state[k]);
  }, {
    immediate: true,
    deep: true
  });
}
```

I found that this code will occasionally log two different values. There seems to be some kind of rare, nondeterministic disorder between when the watcher is executed and the reactive values are updated.

If anyone encounters this same issue, here's my workaround that hasn't failed me yet (just wrap it in a timeout):
```
let writeStore = {};
for (let k in store.state) {
  store.watch(state => state[k], (value) => {
    if (writeStore) {
      clearTimeout(writeStore);
    }
    writeStore[k] = setTimeout(() => console.log(JSON.parse(JSON.stringify(store.state[k]))), 250);
  }, {
    immediate: true,
    deep: true
  });
}
```

**Comment by trusktr** [comment]
None of this works for me. The following attempt returns `null`:

```js
import foo from './foo.vue'
const Foo = Vue.extend(foo)
JSON.stringify(new Foo) // null
```

And fails with circular references, and Vue warning about uninitialized props.

**Comment by Made-of-Clay** [comment]
Alternatively, a `for...in` loop could work too.
```
let data = {};
for (let d in this.$data) {
    data[d] = this.$data[d];
}
```
Not quite as nice to read as the JSON trick, but it's an alternative route. Sadly `for...of` does not work. Womp womp.

**Comment by konojunya** [comment]
It is said that `JSON.parse (JSON.stringify ())` is a good method in this discussion, but I think that using `JSON.stringify` is not a good method.
Because `Date` type etc. are converted to `String`.

As the most effective means, I think best answer @imbolc 's `Object.assign ({}, vm.$data)`.
