### ISSUE TITLE
Question about transitions

### ISSUE THREAD

**Issue by swift1** [vuejs/Discussion#293]
When a transition animation is used on a dynamic component, the new component's html/animation is rendered below the current one and then suddenly jumps in place after the animation is done. Is there any way to prevent that and to get a smooth animation in this case?

https://jsfiddle.net/q7xcbuxd/21/
(Click on "main page")

**Comment by Nirazul** [comment]
You need to fix that in CSS, which is astonishingly easy. Just create a wrapper that holds both elements (enter and leave). And set the leaving one to `position: absolute`.
Vue is really great in handling the hard parts, I realize once again. 

<kbd>[Fiddle](https://jsfiddle.net/q7xcbuxd/25/)</kbd>

**Comment by swift1** [comment]
Thanks for the tips!
