### ISSUE TITLE
Question about custom directives

### ISSUE THREAD

**Issue by swift1** [vuejs/Discussion#301]
Hi guys! Does anyone know why this code works:

````javascript
    <select class="cs-select" v-chosen>
        <option value="Toronto">Toronto</option>
        <option value="Orleans">Orleans</option>
    </select>
````

...while this code doesn't?

````javascript
    <select class="cs-select" v-chosen>
        <template v-repeat="c: cities">
            <option value="{{c}}">{{c}}</option>
        </template>
    </select>
````

http://jsfiddle.net/qfy6s9Lj/5/

**Comment by simplesmiler** [comment]
Probably http://vuejs.org/guide/forms.html#Dynamic_Select_Options

**Comment by swift1** [comment]
Ye, that would have worked if this had been a normal select-box, but it's a custom made element.

So if the code had been:
````
<select v-model="city" options="cities"></select>
````
then it would have worked with 
````
cities: [{text: 'Toronto', value: 'Toronto'}, 
           {text: 'Orleans', value: 'Orleans'}]
````

But ````<select class="cs-select" v-chosen options="cities"></select>```` doesn't work

http://jsfiddle.net/qfy6s9Lj/6/

**Comment by simplesmiler** [comment]
From a quick glace to the [source](https://github.com/yyx990803/vue/blob/dev/src/directives/model/select.js) I can tell that `options` are parsed by `v-model`, and because you are missing `v-model` `options` are ignored.

Fiddle with few other improvements: http://jsfiddle.net/simplesmiler/qfy6s9Lj/8/

**Comment by simplesmiler** [comment]
But it still misses the `options` changes. I do not see a better way other then to copy `v-model`  source for `select` element, modify it so that it notifies chosen, and call it `v-chosen-model`.

Maybe `v-model` should be refactored to make implementation of custom `v-model`-like directives easier.

**Comment by swift1** [comment]
Nice find! Thanks for your contribution. :+1:

**Comment by swift1** [comment]
By the way, there's a little gotcha with custom components that you have to remember to include ````v-model````

For example I was having a ton of trouble with getting the dirty function to work with this date picker, but then I realized that the simple solution was to write
````html
<input type="text" v-model="date" v-datepicker="date" v-validate="required"/>
````
instead of 
````html
<input type="text" v-datepicker="date"/>
````
https://jsfiddle.net/q7xcbuxd/29/

**Comment by swift1** [comment]
@simplesmiler M8, I really appreciate your effort on this matter, but unfortunately, there's a bug in your code.
````
update: function (val) {
	$(this.el).datepicker('setDate', val);
}
````
If ````$(this.el).datepicker('setDate', val);```` is not commented out, then it will be almost impossible to type in the date manually in the text field. Select a date, and then press Ctrl+A while having focus in the text field to type in a date manually. It will default to the year 2070 and the date can only be inserted by either clicking on a date in the date picker or by pasting in a ready-made date into the text field.

**Comment by simplesmiler** [comment]
@swift1 that is what `lazy` is for: https://jsfiddle.net/simplesmiler/q7xcbuxd/34/
I also added `preventDefault` on submit event to avoid jsfiddle submitting the form.

**Comment by swift1** [comment]
Nice! :+1:
