### ISSUE TITLE
Background-size :(

### ISSUE THREAD

**Issue by Mat-Moo** [vuejs/Discussion#304]
http://jsbin.com/qixuqo/edit?html,js,output

When this initially renders the image is as expected, however if I toggle the position, the background-size is lost?

(Probably another stupid one!)

**Comment by adam12** [comment]
I'm not sure what you are trying to achieve exactly, but I suspect maybe your 'background' CSS rule is clobbering 'background-size'.

Reversing the order of the properties in `v-style` might help?

http://jsbin.com/cufulo/edit?html,js,output

**Comment by Mat-Moo** [comment]
No, that's not applying background size at all. If you view my jsbin it works as expected, until an observable changes and then the rules are not fully rep-applied

**Comment by Nirazul** [comment]
I'm not exactly sure what happens in the code. There seems to be some weird implementation logic with `background` shorthand and `background-size`. This is not necessarily a vue bug. When you set the properties one by one, it works:
http://jsbin.com/newifubaru/1/edit?html,js,output

**Comment by Mat-Moo** [comment]
Good call, that works for me, I was struggling to get the right shorthand and size put in as well - will replace with yours, thank you! (And yes needs to be flexible as possible)
