### ISSUE TITLE
Formatting model on event

### ISSUE THREAD

**Issue by lukebro** [vuejs/Discussion#319]
What would be the cleanest way to change the model value when blur fires?  What I essentially need to do is keep this general structure, and when they blur take the input and round it.  All the approaches I've taken so far have been pretty messy and really verbose.

```javascript
new Vue({
     el: '#app',

     data: {
          measurements: {
               height: '',
               width: '',
               depth: '',
          }
});
```

```html
<div id="app">
     <input type="text" v-model="measurements.height" v-on="blur: someFunction">
     <input type="text" v-model="measurements.width" v-on="blur: someFunction">
     <input type="text" v-model="measurements.depth" v-on="blur: someFunction">
</div>
```

Thanks!

**Comment by azamat-sharapov** [comment]
One option is to create your own directive based on [v-model](https://github.com/yyx990803/vue/blob/dev/src/directives/model/text.js). Basically duplicate it and just change events and name of the directive.

**Comment by swift1** [comment]
@lukebro One possible solution:
https://jsfiddle.net/q7xcbuxd/36/

**Comment by lukebro** [comment]
Both your solutions are better than what I came up with, thanks @azamat-sharapov & @swift1
