### ISSUE TITLE
Having trouble with checkboxes and a data array.

### ISSUE THREAD

**Issue by devinfd** [vuejs/Discussion#321]
I'm looking for a way to have a checkbox be checked if it's model value is in a data array. For example:
```
<ul id="v">
  <li v-repeat="row: rows">
    <input type="checkbox" v-model="{{ row.thing }}">
  </li>
</ul>

new Vue({
  el: '#v',
  data: {
    selected: ['foo', 'bar'],
    rows: [{thing: 'foo'}, {thing: 'not'}]
  }
});
```
In the above example if {{ row.thing }} was a value in the `selected` array then I want the checkbox to be checked. I've seen plenty of examples of setting each value as a property in the array with a selected boolean property as well http://jsfiddle.net/yyx990803/1onz2ho7/1/ but in my case each one would be true and that seem kind of ridiculous. How can I achieve what I want? Any guidance is appreciated.

**Comment by swift1** [comment]
Solution:
http://jsfiddle.net/1onz2ho7/2/

![loll](http://thumbs2.ebaystatic.com/d/l225/m/m24QFKALiKM-Dp5Bq1t4SaQ.jpg)

**Comment by kaorun343** [comment]
http://jsfiddle.net/kaorun343/dwut9dp5/
All you have to do is tidy up the data before attaching the dom.

**Comment by devinfd** [comment]
Thank you both for your responses! @swift1 your solution is exactly what I was looking for. I'm happy yet surprised that it works because I thought I read somewhere the docs that `v-model` can not contain computed values which I also took to mean methods.

**Comment by fer-ri** [comment]
@swift1 hi .. seems like if we put model inside methods, then we cant call it directly again

``` js

// data
value = 1

// check methods convert to boolean for checkbox
<input type="checkbox" v-model="check(value)">

// we click checkbox

// not changes here
value = 1
```

any idea?
