### ISSUE TITLE
Can I hook an event when the $el is deleted?

### ISSUE THREAD

**Issue by canjianx** [vuejs/Discussion#329]
I checked the document of 'detached'.  I don't think it's what I want.

Should I check if the vm.$el is in `<body>` in nextTick?  But I don't think it's a good idea.  Do you have any suggest?

Thanks.

**Comment by yyx990803** [comment]
Why isn't `detached` what you want?

**Comment by canjianx** [comment]
It's a legacy code base.  The DOM can be managed by other framework.  And I don't want to add the vue code into the other framework.

**Comment by yyx990803** [comment]
There's no way to detect arbitrary DOM manipulation done by other frameworks, unless you use `MutationObserver`, which is not supported in IE9/10.

**Comment by canjianx** [comment]
Ok.  Thanks.  I think I can use `MutationObserver` in supported browser and a timer in unsupported.
