### ISSUE TITLE
If/else when rendering with v-repeat

### ISSUE THREAD

**Issue by jakeryansmith** [vuejs/Discussion#335]
Sorry if this is a dumb question, but what is the best way to handle if/else when rendering data with v-repeat. For example I have this code:

```<td v-if="item.unit_of_issue === 'weight'">
            <input type="text"
                   v-model="item.weight"
                   class="form-control"
                   tabindex="1"
                   /></td>
        <td v-if="item.unit_of_issue !== 'weight'">
            <input type="text" v-model="item.weight" class="form-control" disabled="disabled"/>
        </td>```

As you can see, I only want weight to be an input field when the items 'unit_of_issue' is equal to weight. But otherwise I want to just render it as plain text. Is my code the correct way to do this, or is there a better way? Do I need the additional if statement? Thanks!

**Comment by lukebro** [comment]
The way I see it what you are doing is perfectly ok.  

You could abstract it by creating a method like issueIsWeight that accepts an item and returns true if unit of issue is weight.  However it's unnecessary, and I would only do it if you find yourself testing a lot to see if the weight is the issue.  
Then you could would `v-if="issueIsWeight(item)"` and `v-if="! issueIsWeight(item)"`.

The latter is a little more readable to understand what's going on, but again if this is the only place you're doing it what you have is perfectly acceptable in my book.

**Comment by jakeryansmith** [comment]
Ok awesome thanks!
