### ISSUE TITLE
Help with debounce

### ISSUE THREAD

**Issue by lukebro** [vuejs/Discussion#338]
Not sure if it's supposed to be like this maybe I'm doing it wrong.  What I'm trying to achieve is a input field where the value is formatted on keyup (to uppercase in example) and then after a 500ms debounce an Ajax request is made.

So the watching of the model and then sending an ajax request works, however the keyup event doesn't fire if the debounce is blocking the model from updating.  Is there any way to have the debounce but still fire keyup event on every stroke?

Here's the fiddle to demo my problem.

Thanks for any help in advance! :)

http://jsfiddle.net/lukebro/16zs91bj/

```html
<div id="app">
    <input type="text" v-model="name" v-on="keyup: format(name)" debounce="500" />
</div>
```

```js
new Vue({
    el: '#app',
    
    data: {
        name: ''   
    },
    
    methods: {
        format: function (val) {
            this.name = val.toUpperCase();
        }
    },
    
    watch: {
        'name': function () {
            console.log("AJAX Request");
        }
    }
});
```

**Comment by swift1** [comment]
http://jsfiddle.net/16zs91bj/1/

**Comment by lukebro** [comment]
@swift1 that's a slight variation but the problem occurs.  The filter isn't applied until after the debounce. 

So what I need is basically this: http://jsfiddle.net/lukebro/k34v0m83/ with a debounce for sending ajax requests only.  Thanks for your response though, any more thoughts?

**Comment by swift1** [comment]
Well, the property does not get written to before the debounce occurs, which is kinda the point of the debounce in the first place. To achieve what you want, you can do something like this instead: http://jsfiddle.net/16zs91bj/2/

**Comment by lukebro** [comment]
@swift1 that's exactly what I was lookin for :+1: thank you for your help! :smile:

**Comment by swift1** [comment]
You're welcome. :)
