### ISSUE TITLE
How to use the babel in vueify？

### ISSUE THREAD

**Issue by chaoren1641** [vuejs/Discussion#351]
I joined in the package.json
```json
"babel-core": "~ 5.8.20",
"babelify": "~ 6.1.3"
```
 and then use the `<script lang = "babel"> `syntax vue file, this time the browser message syntax error, 
es6 code below:

```vue
<script lang="babel">
var evens = [2,4,6,8]
var odds = evens.map(v => v + 1)
module.exports = {
  data: function () {
    return odds
  }
}
</script>
```
Npm developed when using `npm run watch` command:
```shell
"watch": "watchify -v -t vueify src/main.js -t partialify -o build/build.js -dv"
```

Will I missed a step it?

**Comment by chaoren1641** [comment]
木有人回，可能是英文表达不好，@yyx990803 麻烦来看看呀！

**Comment by yyx990803** [comment]
vueify 没法自动用别的 transform，你要先 `npm install babel --save` 然后用 `lang="es6"`.

**Comment by chaoren1641** [comment]
嗯，项目已经用了vueify了，后面会换成vue-loader，多谢，我尝试一下：）
