### ISSUE TITLE
Any way to force re-render?

### ISSUE THREAD

**Issue by CreepGin** [vuejs/Discussion#356]
Didn't find anything in the docs or from online sources. Can you force re-render a Vue instance? 

Also a related question, is it possible to disable caching on the computed properties. In certain cases, I do want the properties to be calculated every time.

**Comment by simplesmiler** [comment]
There's no way I'm aware of. Are you experiencing synchronization issues between view and viewmodel?

**Comment by yyx990803** [comment]
You can turn off caching for computed properties in 0.12.11.

**Comment by CreepGin** [comment]
@simplesmiler My data is a tree and each node's corresponding element's layout (width, height, among other things) depends on it's parents' and sibling's dimensions. Everything can be synchronized if inside the computed properties, the $el dom is fully computed already. But that's not the case. 

I can try to explicitly calculate the dimensions but because my app is responsive layout, this is a lot of work. IMO, the best way would be to somehow have the finished dom $el ready inside of computed properties.

@yyx990803 Thanks! Is this documented anywhere?

**Comment by yyx990803** [comment]
@CreepGin http://vuejs.org/guide/computed.html#Computed_Poperty_Caching

**Comment by CreepGin** [comment]
Ah I see. So the doc was just updated. Thanks!

**Comment by ghost** [comment]
Hi everyone, how does this apply to vue v2 ? I haven't found a way to force a re-render with it.

**Comment by LinusBorg** [comment]
https://vuejs.org/api/#vm-forceUpdate

**Comment by ghost** [comment]
@yyx990803 Hi,
can you advice how to rerender components? I found $forceUpdate but right now confusing while use it.
We have html via AJAX call which contain components. I think it rather common practice for old cms. Can you share please your view on this problem?

**Comment by LinusBorg** [comment]
This repository is deprecated. 

Please use our forum for support questions: forum.vuejs.org

We also have a Gitter chatroom.

**Comment by luowenxing** [comment]
@uharbachou $forceUpdate just take a UI update immediately response to data which only update the dom element needed to be updated according to some algorithm(virtual dom diff in vue2.0 etc) rather than re-render the whole $el . If you want to perform a re-render,there is a way to workaround using `v-if`
```
<template>
    <div v-if="show">
       <button @click="rerender">re-render</button>
    </div>
</template>
<script>
    export default {
        data(){
            return {show:true}
        },
        methods:{
            rerender(){
                this.show = false
                this.$nextTick(() => {
                    this.show = true
                    console.log('re-render start')
                    this.$nextTick(() => {
                        console.log('re-render end')
                    })
                })
            }
        }
    }
</script>
```

**Comment by up9cloud** [comment]
I have v-for issue with nested Array<Object> data.

- https://vuejs.org/v2/guide/list.html#Caveats => not work.
- https://vuejs.org/api/#vm-forceUpdate => not work.
- v-if + $nextTick => It works! Thanks! @luowenxing

**Comment by MaestroJurko** [comment]
I have a similar issue, array is larger than what is rendered with v-for. How to fix this, it is quite urgent.

**Comment by MaestroJurko** [comment]
Ok found a solution, I used push, but I think I found a bug.

Not working with this code:
```
;[].push.apply(vm.comments, body.data.map((vl) => {
   vl.a = modify(vl.a)
  return vl
}))
```

**Comment by matthiasg** [comment]
you can also use `:key="someVariableUnderYourControl"` and change the key when you want to component to be completely rebuilt

**Comment by Gigabiter** [comment]
My way fro ajax update:
`
var data = {'name':'Vasya'};
var vue = new Vue({
    el: '#name',
    data: data
});
fetch('/set_name_url', {
        body: 'name=Ivan'
    }).then(function (response) {
            response.json().then(function (data) {
                //response {'name':'Ivan'}
                for (var key in data) {
                    //reset name Vasya to Ivan in view
                    vue.$set(vue, key, data[key]);
                }
            });
        }
    );
`
`
<div id="name">{{name}}</div>
`

**Comment by intijk** [comment]
@matthiasg You saved the world, I upvoted all your memes :+1:

**Comment by matthiasg** [comment]
@intijk thanks ! The new version of our entire application development platform is based on vue.js and we know a lot of tricks by now :) vue.js is really great, simple and streamlined. most things have pretty straightforward solutions

**Comment by krukid** [comment]
I've had an issue with dynamic translations propagating to `<transition>`-ing elements. Adding `:key="$i18n.locale"` to app layout significantly improved my mental well-being and counts as a solid step toward world peace, I think.

**Comment by AlexKalinin** [comment]
@matthiasg Thanks!

**Comment by OscarVargasG** [comment]
I had a similar problem and i re-render the view using the persisted store. And when i use the router with a param to the same view i use a location.reload()
Because all the HTML is generated by loops over arrays that i fill in the mounted() (in my specific case)
That solves my problem!

**Comment by mihaliak** [comment]
@matthiasg thanks for this hack! 😅
