### ISSUE TITLE
Vuejs no catch attached events to elements added dinamically

### ISSUE THREAD

**Issue by Danjavia** [vuejs/Discussion#372]
I try to catch a click event from a button added dinamically to the site via jQuery but nothing happens. Some idea about this issue.

Thanks!

**Comment by azamat-sharapov** [comment]
You should add button via Vue, not jQuery.

**Comment by Danjavia** [comment]
Sorry for the question, How can I add element in vuejs?

**Comment by azamat-sharapov** [comment]
You can use `v-if` to insert/remove any HTML block.

**Comment by Danjavia** [comment]
I try this

    $( document ).on( 'click', '.owl-carousel' , vm.RemoveSomething );

Thanks guys!
