### ISSUE TITLE
Triggering a method after the change of the props of a component

### ISSUE THREAD

**Issue by kenyiu** [vuejs/Discussion#377]
Hello,
I would like to trigger a method after the change of the props of a component, instead of passing a callback, anyway if i can make it under the component? I have looked through the lifecycle of a componenet on doc, but seems nothing 
Thanks

**Comment by azamat-sharapov** [comment]
Maybe `vm.$watch()` can help? You can find it on API docs

**Comment by kenyiu** [comment]
@azamat-sharapov thanks for the keyword!
Found this fit my case:http://vuejs.org/api/options.html#watch
