### ISSUE TITLE
Is it possible to add computed property after a VM has been instantiated?

### ISSUE THREAD

**Issue by lilchow** [vuejs/Discussion#383]
Let's say I first instantiated a new VM:
```
var vm= new Vue({
	data: {sex: 'male', uni:'marvel'},
	computed: {
		sexuni: function () {
			return this.sex + '@' + this.uni;
		}
	}
});
```

Then at a later point, I wanted to add a new computed property `unisex` which should return `this.uni@this.sex`. Is this possible to do?

**Comment by Mat-Moo** [comment]
Can I ask why you wouldn't just create that before hand? Just trying to understand what you want to achieve

**Comment by lilchow** [comment]
I want the users of my app to be able to create computed properties on fly without knowing the underlying implementation. In other words, they can decide to add some new computed properties at any time while the app is running by calling a single command such as myApp.addCompProp(propName,formula). I can work around this but I just want to know if it is possible because $set method can only work with $data obj. BTW, the target users of my app will be mostly JS illiterate.

**Comment by simplesmiler** [comment]
You probably should not give users access to the framework internals, and instead should describe your application logic on top of it. E.g. you can store `formulas` as a list of expressions in some expression language, and have a computed property `results` as a list of formulas.

**Comment by lilchow** [comment]
So it seems that it is not possible. Thanks!
