### ISSUE TITLE
Vue filter export

### ISSUE THREAD

**Issue by oleynikd** [vuejs/Discussion#401]
Hi,

Dear @yyx990803, can I somehow export Vue filter for importing it with `require()` for ex. using [vueify](https://github.com/vuejs/vueify)? Something like we do with `.vue` one-file components... I guess I've seen some implementation but I can't find it...(

I've tried something like this:
```JS
module.exports = function (arg1, arg2) {
    return ...
}
```

And
```JS
...
filters: {
    myFilter: require('../../filters/myFilter.js')
},
...
```
But this does not work when I try:
```JS
var filter = Vue.filter('myFilter');
```

Thanks in advance.

**Comment by yyx990803** [comment]
`Vue.filter()` only returns globally registered filters. If you just need the function, you don't need to register it as a filter... just `require` it in the code that needs it.

**Comment by oleynikd** [comment]
Oh... I feel so stupid! This is super obvious! I guess I overVued this...
Thanks a lot once again!!!
