### ISSUE TITLE
Disable Dynamic Select Options

### ISSUE THREAD

**Issue by Arnaud-Woufbox** [vuejs/Discussion#419]
Hi !

I don't want use the Dynamic Select Options, i want to v-repeat options in my select because I don't want to rebuild an object like  { text: 'A', value: 'a' }  just for that !!!

Have you got an issue about that ?

thanks

**Comment by simplesmiler** [comment]
In 0.12 you can not `<option v-repeat="...">`, this will just not work. The best you can do is to write a filter that transforms your data to the format, expected by the `options`.

In 1.0 it will be possible to `<option v-for="...">`.

**Comment by Arnaud-Woufbox** [comment]
Tanks @simplesmiler for your answer
