### ISSUE TITLE
v-autocomplete?

### ISSUE THREAD

**Issue by gaydenko** [vuejs/Discussion#43]
Being at the moment a Knockout user, I use this [1] excellent wrapper around jQuery UI autocompletion plugin. What is the Vue.js way?

[1] https://github.com/rniemeyer/knockout-jqAutocomplete

**Comment by Theviajerock** [comment]
gaydenko, i have the same trouble with that.....

**Comment by dcorb** [comment]
I found this project. I haven't used it still https://github.com/pespantelis/vue-typeahead
