### ISSUE TITLE
Select2 on Modal component [Not working]

### ISSUE THREAD

**Issue by gredimano** [vuejs/Discussion#467]
Hi, I create a modal using this new component of vue http://vuejs.org/examples/modal.html. And then add a select2 inside the component(modal), i displayed the select2 but its not clickable.  

Thanks

**Comment by boosis** [comment]
Did you manage to solve your problem?

**Comment by gredimano** [comment]
Hi, Yes. 
Thanks for your concern.

**Comment by wbnx** [comment]
Can you share how you fixed this problem?

**Comment by ciiichy** [comment]
I have similar problem, can you share how you fixed this problem?
