### ISSUE TITLE
Custom Directive as browserify module not working

### ISSUE THREAD

**Issue by noahmatisoff** [vuejs/Discussion#476]
I have a simple custom directive that I haven't added any functionality to: it's sitting in `app/directives/currency.js`:

``` javascript
module.exports = {
  update: function(newValue, oldValue) {
    console.log(newValue)
    console.log(oldValue)
  },
  bind: function() {

  },
  unbind: function() {

  }
}
```

And then in my Vue component, I have something like this:

``` javascript
module.exports = {
  template: require('./template.html'),
  directives: {
    currency: require('./directives/currency.js')
  }
}
```

But when I attach `currency` to a text input, nothing is being logged to the console.  What is wrong with this?

**Comment by noahmatisoff** [comment]
Needed v-*, my bad.

**Comment by FWSimon** [comment]
hm i tried the same here, but it keep saying `Failed to resolve directive: test2` and i have the v-test2

**Comment by noahmatisoff** [comment]
@FWSimon post code I'll let you know if I see anything that may be causing it.

**Comment by FWSimon** [comment]
Thanks @matisoffn i found out that it was because i needed to include the directive into my component :+1: Thanks

**Comment by cnweibo** [comment]
thanks, it save me 1 hour
