### ISSUE TITLE
How works reactive store sync?

### ISSUE THREAD

**Issue by renatorib** [vuejs/Discussion#479]
Hello,
In my project, I have this store: 

``` js
var items = {
  data: [],
  fetch: function(query){
    doAsyncFetch(query, function(resData){
      Vue.set(this, 'data', resData);
    });
  }
}
```

And in my component, I've setted:

``` js
Vue.component('page-items', {
  data: function(){ 
    return {
      items: items.data
    }
  }
});
```

But when I fetch store with `items.fetch(someQuery)`, the `items.data` are updated, but `$vm.items` don't update.

![image](https://cloud.githubusercontent.com/assets/3277185/12087087/3bbf3fec-b2b7-11e5-81cd-5e9bf40fdb1f.png)

If I replace `Vue.set(this, 'data', resData);` for `this.data = resData` doesn't works too.
The only way that works is when I use `items.data.push({});`, but I can't push an entire array, I need replace.

Help me understand how works reactive sync, please.
Thanks!

**Comment by renatorib** [comment]
Well, It worked with jQuery extend (or underscore/lodash extend)

``` js
$.extend(this.data, resData);
```

But I still don't understand how it works.

**Comment by Jokcy** [comment]
```
var items = {
  data: [],
  fetch: function(query){
    doAsyncFetch(query, function(resData){
      Vue.set(this, 'data', resData);
    });
  }
}
```

are sure **'this'** is really **'this'**?

**Comment by renatorib** [comment]
Yes, it's only an example I've writed, but is really 'this'. 

I already solved this problem in vue forums :D
Thanks

**Comment by narazin** [comment]
Can you share your solve?

**Comment by renatorib** [comment]
1 year ago, I don't remember, sorry.
