### ISSUE TITLE
Partial inside component

### ISSUE THREAD

**Issue by EmilMoe** [vuejs/Discussion#491]
I have a component A which uses another component B. This B component allows me to use partials, so my question is, how do I register a partial only inside the scope of component A?

**Comment by coblan** [comment]
`Vue.component('componentA',{
                template:'#XXX',
                props:[],
                partials:{
                    dog:'<div>this is dog</div>',
                    pig:'<div>this is pig</div>',
                }
            })`

**Comment by execjosh** [comment]
But, what if I want the templates for the partials to come from the DOM with a selector, like with the template for the component?  Does this have to be done manually?
