### ISSUE TITLE
How to use the correct component implementation in vue file list

### ISSUE THREAD

**Issue by lee134134134** [vuejs/Discussion#497]
Home.vue
<template lang="jade">
  .page-group
    .page
      bar(title="DEMO")
      .content
        .content
          p.tip-title Aoyou. Not Production Ready(v0.1).
          .list-block
            list(v-bind:items="listDatas")
</template>

<style lang="scss">
  .tip-title{
    text-align: center;
    margin: 0;
    font-size: (14rem/20);
    line-height: 1rem;
    color: #000;
  }
  .list-icon{
    color: #E94709;
  }
</style>

<script>
  import Bar from '../components/Bar'
  import List from '../components/List'

  export default {
    components: {
      Bar,
      Lists
    },
    data: {
      listDatas: [
        {message:'list1'},
        {message:'list2'}
      ]
    }
  }
</script>

List.vue

<template lang="jade">
  ul
    li.item-content(v-for="item in items")
      .item-media
        slot
      .item-inner
        .item-title {{item}}
        .item-after.item-after-arrow
</template>

<style lang="scss">
</style>

<script>
  export default{
    props: {
      title: []
    }
  }
</script>

This will be an error But can you tell me how to write correct？Tanks

**Comment by simplesmiler** [comment]
Hello!

We don't use `vuejs/Discussion` anymore, and encourage you to ask usage questions on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue).

It would help if you could provide a live reproduction (with [jsfiddle](https://jsfiddle.net/simplesmiler/Lrk9sxjf/) for example).
