### ISSUE TITLE
Flow control syntax

### ISSUE THREAD

**Issue by yyx990803** [vuejs/Discussion#62]
### Comment based

``` html
<!-- v-repeat="item:items" -->
  <div>{{item.title}}</div>
  <div>{{item.content}}</div>
<!-- v-repeat-end -->
```
- pros: easier to parse
- cons: yet another type of syntax
### Handlebars style

``` handlebars
{{#repeat item:items}}
  <div>{{item.title}}</div>
  <div>{{item.content}}</div>
{{/repeat}}

{{#if user.loggedIn}}
  <h1>Welcome!</h1>
  <p>{{user.name}}</p>
{{/if}}

{{> some-partial}}
```
- pros: familiarity, looks better
- cons: harder to parse
### Custom element style

``` html
<v-repeat model="items" as="item">
  <div>{{item.title}}</div>
  <div>{{item.content}}</div>
</v-repeat>

<v-if condition="user.loggedIn">
  <h1>Welcome!</h1>
  <p>{{user.name}}</p>
</v-if>

<v-partial ref="some-partial"></v-partial>
```
- pros: easiest to parse
- cons: a bit more verbose; using elements for abstract concepts like flow control seems to be semantically inconsistent.

---

Which one do you prefer?

**Comment by ShahanurSharif** [comment]
http://jsbin.com/cocavu/edit?html,js,output
I am trying to do something like this but its not working

```
<span v-if="item.message==AppUser">I am followed</span>
```
