### ISSUE TITLE
Best way to pass data to a component

### ISSUE THREAD

**Issue by rafaelrinaldi** [vuejs/Discussion#64]
What's the best/standard way to pass data to a component I'm registering? I was thinking about something like this:

``` js
// Creating a new component
var Component = Vue.extend({
  ready: function() {
    // Print value that was passed on registration
    console.log(this.foo); // bar
  }
});

// Pass a hash when registering a new component
Vue.component('my-component', Component, {foo: 'bar'});
```

This is useful when you want a dynamic startup value.

**Comment by bubnenkoff** [comment]
Am I right understand that `data` should include all data that component have. I mean all of them should be **inside** of `data`? Or I can create some outside?

And what is `ready` and `created`? Is it keywords?

**Comment by rafaelrinaldi** [comment]
@bubnenkoff You can simply use the component model layer.

**Comment by axel22** [comment]
What about `props` - is it possible to pass them when creating the component manually?

**Comment by LinusBorg** [comment]
@axel22 

``` js
var instance = new MyComponent({ 
  propsData: { ...}
})
```

**Comment by axel22** [comment]
@LinusBorg Thanks a lot! Interestingly, I found that if `MyComponent` has `props` defined, passing `data` somehow works for me, but `propsData` does not. Not sure why that is, but it seems that just using `data` solves my problem:

```
var instance = new MyComponent({ 
  data: { ... }
})
```
