### ISSUE TITLE
Transitions/Effects for v-show

### ISSUE THREAD

**Issue by rdsubhas** [vuejs/Discussion#67]
Hi, I love the way transitions/effects have been simplified in next. But the only crib is that they work only when DOM is being added/removed. There are many cases (like say an off-screen menu, tab switches or popup menus/dialogs) where we'd like transitions for v-show, but after the end of the transition, instead of removing the div - it should simply hide it (set `display: none`). This is not possible with plain CSS classes and transitions (using v-class) right now, because we can change animatable properties (like opacity) of the div using CSS transitions, but it doesn't really hide and will still be receiving mouse pointer events and messes up the screen. Unless we use some Javascript library like jquery.Transit or Velocity, its a pain to **really hide** the div after transition completes, and this is becoming a common need across our codebase using Vue right now.

Is it possible to make the Transitions API to support both Insertion/Removal and Show/Hide of DOM elements? I see that internally it works on a series of callbacks (like say `done` in `leave` hook), so would it be semantically possible to have `v-if/v-component/v-view/etc` use a callback that inserts/removes elements, and `v-show` to use a callback that shows/hides elements upon transitionend/animationend?

Or if a javascript effect is being used - would it be possible to make the `done` function to either insert/remove or show/hide based on the directive, so that the effect code will need no changes, but what happens after the effect is left to the actual directive...

**Comment by priya2521** [comment]
why bootstrap carousel transition is not working with vue.js?? any idea??
