### ISSUE TITLE
how can I use <script type="x-template"> trick to include templates?

### ISSUE THREAD

**Issue by huyaxiong** [vuejs/Discussion#69]
I am a beginner and I can not understand the meaning of  'This allows the use of the common 
script type="x-template" trick to include templates' in your api doc,I just don't want to include templates using a html string pattern or use browserify like require('./template.html') because my ide doesn't support it very well and browserify is a little hard for me to learn.So can you give me an easy example of this "x-template" way to include my template or other way easy to learn,thank you!

**Comment by rodanato** [comment]
Hi, i have some issues using vuetable in IE because of the template tag, i try to change it to script tag but doesnt work, can you @yyx990803 please show an example of component that includes html, js and css ?

**Comment by simplesmiler** [comment]
@rodanato 

We don't use `vuejs/Discussion` anymore, and encourage you to ask usage questions on [forum](https://forum.vuejs.org/) or [gitter](https://gitter.im/vuejs/vue).

**Comment by syshex** [comment]
@rodanato  Hey, any luck with that ?

**Comment by rodanato** [comment]
Hi, I'm not using it lately but If I'm nos wrong, someone mentioned a possible solution in Vue2.

**Comment by rashnk** [comment]
is possible ?
```
<script type="x-template" id="my-template" src="template.js"> </script>
<div id="app"></div>
```

**Comment by maleta** [comment]
This could be solution:
https://github.com/vuejs/Discussion/issues/313

**Comment by dhanasethupathy** [comment]
can any one please give me a syntax or x-template for table row that could be very help full to me
