### ISSUE TITLE
Accessing child component data inside expression on parent

### ISSUE THREAD

**Issue by Pistos** [vuejs/Discussion#75]
I've tried many different things for a few hours, having read nearly all the Guide and API documentation.  Here is what I have so far.  It's one of several approaches I've tried for creating and associating/relating a parent and a child, but this seems closest to success:

http://jsfiddle.net/3odb3euv/8/

I have an outer div, with an inner span, and a Vue ViewModel for each.  I want to get at data of the child from within, say, a `v-attr` attribute on the parent.  In the case of version 8 of the fiddle above, on line 12, within the `computedN` function, the parent-child relationship doesn't seem to be established yet by the time it executes `computedN` for the first time (the console error is "Uncaught TypeError: Cannot read property 'n' of undefined").  I know the relationship is eventually established, because the `console.log` calls at the end print out what I expect.

How can I get at the child's `n` value from within `v-attr`?

**Comment by movostudios** [comment]
Hey. Is there an example of how to set the page title? I'm just picking up Vue (Awesome by the way) and I'm not getting to grips well with instances talking to each other.

Cheers

**Comment by swift1** [comment]
There are many ways to communicate between the parent and the child, or to share data:
1. ```v-with```, from child to parent
2. ```inherit: true``` in the child component
3. pass data as ```props``` to the child
4. reference the child with ```this.$.childRef``` and reference the parent from the child with ```this.$parent```
5. pass messages between components with ```$emit```
6. share data by importing mixins with common functions

**Comment by movostudios** [comment]
Thanks at @swift1. Much appreciated. I have been playing with $emit. Ive yet to figure out how to listen for it on the parent. I'm not that familiar with JS frameworks, so reliant on the docs and example.  Do you know of any example on broadcasting and listening to events?

Cheers

**Comment by swift1** [comment]
https://jsfiddle.net/9678Lor5/9/

**Comment by movostudios** [comment]
Ahhhh. Thanks so much @swift1. That makes sense. Just got to change my thinking a little. Thanks for taking the time to help. Very much appreciated!! Legend!

**Comment by MJ111** [comment]
for future reader: In v0.12 release, v-with deprecated. One-way data flow which is parent to child is recommended
