### ISSUE TITLE
Trigger recompile?

### ISSUE THREAD

**Issue by Pistos** [vuejs/Discussion#77]
It's entirely possible that I am approaching this wrong, or not in a Vue.js way.  However, I am slowly trying to migrate an existing jQuery application to use more and more Vue.js, so it isn't so easy for me to just start from scratch.

I have a parent DOM element which I created a VM for with `new Vue`, and then children DOM elements that I put a `v-component` attribute on.  This is fine, and is working for me.  However, when I later inject (with AJAX and jQuery DOM insertion) new DOM elements that have the same `v-component` on them, they are not compiled or adopted by Vue.js, even though these new, injected elements are also children of the parent DOM element.

Is there a way to tell the parent to recompile itself, so that it rescans its inner DOM, and "activates" the injected component elements?  Or is there a different and better way to design this whole thing?

I should mention that we are avoiding heavy JS-side templating (at least for now) because we would like to keep i18n server-side instead of JS-side.

**Comment by chrise86** [comment]
Is such a thing possible in v2?

**Comment by ciarans** [comment]
+1 would like to recompile a new element

**Comment by lmartins** [comment]
Have anyone found a way to achieve this in v2?

**Comment by Pistos** [comment]
My solution should still work for v2?
