### ISSUE TITLE
Clearer explanation of created/ready/attached

### ISSUE THREAD

**Issue by malkomalko** [vuejs/Discussion#8]
It looks like the dom is ready in the attached state, and created can be used to manipulate $data before it goes into the compilation phase, but what is ready used for?

Just trying to get a clear picture in my head for these lifecycle events.  I've read the docs but maybe a quick "When should you use these lifecycle events".

Thoughts?

**Comment by jedierikb** [comment]
http://vuejs.org/api/#created
