### ISSUE TITLE
[0.11] Send click event (jQuery click() not received)

### ISSUE THREAD

**Issue by Pistos** [vuejs/Discussion#80]
I have a method on my VM that is set up to be called with `v-on="click: onClick"`.  Naturally, it takes an event parameter: `onClick: function(event) {...}`.  It works just fine when I physically click on the element in question.  However, when I issue a click event with jQuery: `$('a.foobar').click()`, the method does not get called.  I suppose this is because jQuery does not actually fire a native click event, but rather just scans its own internal list of click handlers.

How do I send a click event with Vue.js, then?  Should I just construct my own fake `event` object, then call `vm.onClick(fakeEvent)` myself?

**Comment by ghost** [comment]
This `$('element')[0].click()` did work for me.
